import { useCallback, useEffect, useState } from "react";
import { View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { toLocalDateKey, type RecordingTask, type TaskAction } from "@postai/domain";
import { ensureDayPlan, listContent, listTasks, runTaskAction, type ContentItem } from "../../src/db/repo";
import { autoGenerateDay, generateForContent } from "../../src/generate";
import { scheduleTaskReminders } from "../../src/notifications";
import { getSyncStatus, subscribeSync } from "../../src/sync/engine";
import { syncLabel } from "../../src/sync/label";
import { reportError } from "../../src/telemetry";
import { useApp } from "../../src/app-state";
import { TodayView } from "../../src/components/TodayView";
import { UpdateBanner } from "../../src/components/UpdateBanner";
import { createFreeSpeech, importVideo } from "../../src/freeSpeech";
import { ProfileSwitcher } from "../../src/components/ProfileSwitcher";
import { Button, ErrorBox, Loading, Screen } from "../../src/ui";

export default function Today() {
  const { workspace } = useApp();
  const [state, setState] = useState<{ tasks: RecordingTask[]; contents: ContentItem[] } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [now, setNow] = useState(new Date());
  const [generatingId, setGeneratingId] = useState<string | null>(null);
  const [sync, setSync] = useState(getSyncStatus());
  const [quick, setQuick] = useState<string | null>(null);

  async function quickStart(label: string, fn: () => Promise<void>) {
    setQuick(label);
    setError(null);
    try {
      await fn();
    } catch (e) {
      reportError(e, label);
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setQuick(null);
    }
  }

  useEffect(() => subscribeSync(setSync), []);

  const load = useCallback(async () => {
    try {
      const today = new Date();
      setNow(today);
      await ensureDayPlan(today);
      const key = toLocalDateKey(today);
      const [tasks, contents] = await Promise.all([listTasks(key), listContent(key)]);
      setState({ tasks, contents });
      setError(null);
      // the app prepares the day's scripts by itself; the creator only records
      if (contents.some((c) => !c.draft)) {
        autoGenerateDay(contents, () => void listContent(key).then((cs) => setState((st) => (st ? { ...st, contents: cs } : st))))
          .catch((e) => reportError(e, "auto generate"));
      }
      if (workspace) scheduleTaskReminders(tasks, workspace.settings.reminders).catch((e) => reportError(e, "reminders"));
    } catch (e) {
      reportError(e, "today load");
      setError("Não consegui carregar o seu dia. Seus dados continuam salvos no aparelho.");
    }
  }, [workspace]);

  useFocusEffect(useCallback(() => void load(), [load]));
  useEffect(() => {
    const t = setInterval(() => setNow(new Date()), 60_000);
    return () => clearInterval(t);
  }, []);

  async function onAction(task: RecordingTask, action: TaskAction) {
    try {
      await runTaskAction(task.id, action);
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  async function onGenerate(contentId: string) {
    setGeneratingId(contentId);
    try {
      await generateForContent(contentId);
      router.push(`/content/${contentId}`);
    } catch (e) {
      reportError(e, "generate");
      setError("Não consegui gerar o roteiro agora. Tente de novo.");
    } finally {
      setGeneratingId(null);
      void load();
    }
  }

  if (!state && !error) return <Screen><Loading label="Montando o seu dia…" /></Screen>;
  return (
    <Screen testID="today-screen">
      <UpdateBanner />
      <ProfileSwitcher />
      <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>
        <Button compact variant="secondary" label="🎙 FALA LIVRE (sem roteiro)" loading={quick === "fala"} testID="free-speech" onPress={() => void quickStart("fala", async () => {
          const c = await createFreeSpeech("gravar");
          router.push({ pathname: "/record", params: { contentId: c.id } });
        })} />
        <Button compact variant="secondary" label="📥 IMPORTAR VÍDEO" loading={quick === "importar"} testID="import-video" onPress={() => void quickStart("importar", async () => {
          const c = await importVideo();
          if (c) router.push(`/finalizar/${c.id}`);
        })} />
      </View>
      {workspace?.profile.kind === "empresa" ? (
        <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>
          <Button compact label="🎥 NOVO PROJETO NO ESTÚDIO" onPress={() => router.push("/projeto")} testID="open-projeto" />
          {workspace.cloud ? <Button compact variant="secondary" label="🎓 CURSO" onPress={() => router.push("/curso")} testID="open-curso" /> : null}
          {workspace.cloud ? <Button compact variant="secondary" label="🎬 PATRIMÔNIO" onPress={() => router.push("/patrimonio")} testID="open-patrimonio" /> : null}
        </View>
      ) : null}
      {error ? <ErrorBox message={error} onRetry={load} /> : null}
      {state ? (
        <TodayView
          now={now}
          tasks={state.tasks}
          contents={state.contents}
          syncLabel={syncLabel(sync, Boolean(workspace?.cloud))}
          generatingId={generatingId}
          onAction={onAction}
          onRecord={(t) => router.push({ pathname: "/record", params: { taskId: t.id, contentId: t.contentItemId ?? "", partes: t.contentItemId ? "1" : "0" } })}
          onOpenContent={(id) => router.push(`/content/${id}`)}
          onGenerate={onGenerate}
          onEvent={() => router.push("/event")}
          onFreeRecord={() => router.push("/record")}
          pillarNames={Object.fromEntries((workspace?.pillars ?? []).map((pl) => [pl.slug, pl.name]))}
        />
      ) : null}
    </Screen>
  );
}
