import { useCallback, useEffect, useState } from "react";
import { View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { toLocalDateKey, type RecordingTask, type TaskAction } from "@postai/domain";
import { ensureDayPlan, listContent, listTasks, runTaskAction, type ContentItem } from "../../src/db/repo";
import { autoGenerateDay, generateForContent } from "../../src/generate";
import { scheduleTaskReminders } from "../../src/notifications";
import { getSyncStatus, subscribeSync } from "../../src/sync/engine";
import { syncLabel } from "../../src/sync/label";
import { reportError } from "../../src/telemetry";
import { useApp } from "../../src/app-state";
import { TodayView } from "../../src/components/TodayView";
import { UpdateBanner } from "../../src/components/UpdateBanner";
import { createFreeSpeech, importVideo } from "../../src/freeSpeech";
import { ProfileSwitcher } from "../../src/components/ProfileSwitcher";
import { Button, Card, ErrorBox, Loading, Screen, s } from "../../src/ui";

export default function Today() {
  const { workspace } = useApp();
  const [state, setState] = useState<{ tasks: RecordingTask[]; contents: ContentItem[] } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [now, setNow] = useState(new Date());
  const [generatingId, setGeneratingId] = useState<string | null>(null);
  const [sync, setSync] = useState(getSyncStatus());
  const [quick, setQuick] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);

  async function quickStart(label: string, fn: () => Promise<void>) {
    setQuick(label);
    setError(null);
    try {
      await fn();
    } catch (e) {
      reportError(e, label);
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setQuick(null);
    }
  }

  useEffect(() => subscribeSync(setSync), []);

  const load = useCallback(async () => {
    try {
      const today = new Date();
      setNow(today);
      await ensureDayPlan(today);
      const key = toLocalDateKey(today);
      const [tasks, contents] = await Promise.all([listTasks(key), listContent(key)]);
      setState({ tasks, contents });
      setError(null);
      if (contents.some((c) => !c.draft)) {
        autoGenerateDay(contents, () => void listContent(key).then((cs) => setState((st) => (st ? { ...st, contents: cs } : st))))
          .catch((e) => reportError(e, "auto generate"));
      }
      if (workspace) scheduleTaskReminders(tasks, workspace.settings.reminders).catch((e) => reportError(e, "reminders"));
    } catch (e) {
      reportError(e, "today load");
      setError("Não consegui carregar o seu dia. Seus dados continuam salvos no aparelho.");
    }
  }, [workspace]);

  useFocusEffect(useCallback(() => void load(), [load]));
  useEffect(() => {
    const t = setInterval(() => setNow(new Date()), 60_000);
    return () => clearInterval(t);
  }, []);

  async function onAction(task: RecordingTask, action: TaskAction) {
    try {
      await runTaskAction(task.id, action);
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  async function onGenerate(contentId: string) {
    setGeneratingId(contentId);
    try {
      await generateForContent(contentId);
      router.push(`/content/${contentId}`);
    } catch (e) {
      reportError(e, "generate");
      setError("Não consegui gerar o roteiro agora. Tente de novo.");
    } finally {
      setGeneratingId(null);
      void load();
    }
  }

  const createMenu = (
    <View style={{ gap: 10 }}>
      <Button variant="secondary" label={createOpen ? "FECHAR" : "+ CRIAR OUTRA COISA"} onPress={() => setCreateOpen((v) => !v)} testID="open-create" />
      {createOpen ? (
        <Card style={{ gap: 10 }} testID="create-menu">
          <Button label="🎬 GRAVAR O QUE O DIRETOR PEDIU" onPress={() => router.push("/(tabs)/gravar")} testID="create-director-record" />
          <Button variant="secondary" label="🎙 FALAR LIVRE" loading={quick === "fala"} testID="free-speech" onPress={() => void quickStart("fala", async () => {
            const c = await createFreeSpeech("gravar");
            router.push({ pathname: "/record", params: { contentId: c.id } });
          })} />
          <Button variant="secondary" label="📥 IMPORTAR VÍDEO" loading={quick === "importar"} testID="import-video" onPress={() => void quickStart("importar", async () => {
            const c = await importVideo();
            if (c) router.push(`/finalizar/${c.id}`);
          })} />
          <Button variant="secondary" label="🎞 CENA DE APOIO (B-ROLL)" onPress={() => router.push("/record")} testID="create-broll" />
          {workspace?.profile.kind === "empresa" ? (
            <View style={{ gap: 8 }}>
              <Button variant="secondary" label="🏭 GRAVAR PRODUTO / PROVA" onPress={() => router.push("/projeto")} testID="open-projeto" />
              {workspace.cloud ? <Button variant="ghost" label="🎓 CURSO" onPress={() => router.push("/curso")} testID="open-curso" /> : null}
              {workspace.cloud ? <Button variant="ghost" label="📦 PATRIMÔNIO / PEDIDO" onPress={() => router.push("/patrimonio")} testID="open-patrimonio" /> : null}
            </View>
          ) : null}
        </Card>
      ) : null}
    </View>
  );

  if (!state && !error) return <Screen><Loading label="Montando o seu dia…" /></Screen>;
  return (
    <Screen testID="today-screen">
      <UpdateBanner />
      <View style={[s.row, { alignItems: "center", gap: 8 }]}>
        <View style={{ flex: 1 }}><ProfileSwitcher /></View>
        <Button compact variant="ghost" label="Estratégia" onPress={() => router.push("/(tabs)/plano")} testID="open-plan" />
      </View>

      {error ? <ErrorBox message={error} onRetry={load} /> : null}
      {state ? (
        <TodayView
          now={now}
          tasks={state.tasks}
          contents={state.contents}
          syncLabel={syncLabel(sync, Boolean(workspace?.cloud))}
          generatingId={generatingId}
          onAction={onAction}
          onRecord={(t) => router.push({ pathname: "/record", params: { taskId: t.id, contentId: t.contentItemId ?? "", partes: t.contentItemId ? "1" : "0" } })}
          onOpenContent={(id) => router.push(`/content/${id}`)}
          onGenerate={onGenerate}
          onEvent={() => router.push("/event")}
          onFreeRecord={() => router.push("/record")}
          createSlot={createMenu}
          pillarNames={Object.fromEntries((workspace?.pillars ?? []).map((pl) => [pl.slug, pl.name]))}
        />
      ) : null}
    </Screen>
  );
}
