// GENERATED by apps/api build:edge — do not edit

// ../../packages/domain/src/pillars.ts
var RODRIGO_PILLARS = [
  { slug: "reflexao", name: "Motiva\xE7\xE3o e reflex\xE3o real", targetPercent: 40 },
  { slug: "vida-real", name: "Vida real / homem 40+ / maturidade", targetPercent: 20 },
  { slug: "academia", name: "Academia e evolu\xE7\xE3o", targetPercent: 15 },
  { slug: "familia", name: "Fam\xEDlia", targetPercent: 10 },
  { slug: "humor", name: "Humor", targetPercent: 10 },
  { slug: "empreendedorismo", name: "Empreendedorismo", targetPercent: 5 }
];

// ../../packages/domain/src/planner.ts
var RODRIGO_WEEKDAY_BLOCKS = [
  { startTime: "08:45", title: "Caf\xE9 / B-roll", contentHint: "3 segundos do caf\xE9", optional: false, format: "broll" },
  { startTime: "09:10", title: "In\xEDcio do trabalho / B-roll", contentHint: "entrada no expediente", optional: false, format: "broll" },
  { startTime: "10:30", title: "Pensamento do Dia", contentHint: "v\xEDdeo curto 5\u201315s", optional: false, format: "thought" },
  { startTime: "12:15", title: "Almo\xE7o opcional", contentHint: "take de 3 segundos", optional: true, format: "broll" },
  { startTime: "15:00", title: "Trabalho / B-roll", contentHint: "algo real acontecendo na empresa", optional: true, format: "broll" },
  { startTime: "17:30", title: "Fim do expediente", contentHint: "encerramento do trabalho", optional: false, format: "broll" },
  { startTime: "19:15", title: "Prepara\xE7\xE3o para academia", contentHint: "pr\xE9-treino / prepara\xE7\xE3o", optional: false, format: "broll" },
  { startTime: "19:30", title: "V\xEDdeo principal caminhando", contentHint: "45s\u20132m", optional: false, format: "main_video" },
  { startTime: "20:15", title: "Academia / B-roll", contentHint: "entrada, exerc\xEDcio ou final", optional: false, format: "broll" },
  { startTime: "21:30", title: "Fim do dia", contentHint: "encerramento", optional: false, format: "broll" }
];
function rodrigoRoutine(newId) {
  const blocks = [];
  for (let weekday = 1; weekday <= 5; weekday++) {
    for (const b of RODRIGO_WEEKDAY_BLOCKS) blocks.push({ ...b, id: newId(), weekday });
  }
  return blocks;
}

// ../../packages/domain/src/repetition.ts
var DEFAULT_REPETITION_CONFIG = {
  thresholds: { topic: 0.5, phrase: 0.45, metaphor: 0.5, hook: 0.5 },
  ctaMaxRepeats: 2,
  structureMaxInWindow: 3,
  structureWindow: 5
};
var STOPWORDS = new Set(
  "a o as os um uma uns umas de da do das dos em na no nas nos por para pra pro com sem e ou que se me te nos voce voces eu ele ela eles elas isso isto esse essa este esta aquilo mais menos muito muita ja nao sim so ao aos \xE0 \xE0s \xE9 era ser foi vai vou ter tem tinha sua seu suas seus minha meu minhas meus tua teu como quando onde porque pq mas entao ent\xE3o hoje".split(
    " "
  ).map((w) => stripAccents(w))
);
function stripAccents(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "");
}
function normalizeText(s) {
  return stripAccents(s.toLowerCase()).replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();
}
function stem(w) {
  return w.length > 4 ? w.replace(/(mente|coes|cao|oes|ais|eis|res|es|as|os|s)$/u, "") : w;
}
function contentTokens(s) {
  return normalizeText(s).split(" ").filter((w) => w.length > 1 && !STOPWORDS.has(w)).map(stem);
}
function similarity(a, b) {
  const ta = contentTokens(a);
  const tb = contentTokens(b);
  if (ta.length === 0 || tb.length === 0) return 0;
  const uni = jaccard(new Set(ta), new Set(tb));
  const bi = jaccard(bigrams(ta), bigrams(tb));
  const small = ta.length <= tb.length ? ta : tb;
  const big = new Set(ta.length <= tb.length ? tb : ta);
  const containment = small.length >= 3 ? small.filter((w) => big.has(w)).length / small.length : 0;
  return round(Math.max(uni, bi, containment * 0.9));
}
function bigrams(tokens) {
  const s = /* @__PURE__ */ new Set();
  for (let i = 0; i < tokens.length - 1; i++) s.add(`${tokens[i]} ${tokens[i + 1]}`);
  return s;
}
function jaccard(a, b) {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter++;
  return inter / (a.size + b.size - inter);
}
function fingerprintsFor(draft) {
  const fps = [
    { type: "topic", value: normalizeText(draft.topic) },
    { type: "phrase", value: normalizeText(draft.key_phrase) },
    { type: "cta", value: normalizeText(draft.cta) },
    { type: "structure", value: draft.structure }
  ];
  if (draft.metaphor.trim()) fps.push({ type: "metaphor", value: normalizeText(draft.metaphor) });
  for (const h of draft.hook_options) fps.push({ type: "hook", value: normalizeText(h) });
  return fps.filter((f) => f.value.length > 0);
}
function checkRepetition(candidate, recent, config = DEFAULT_REPETITION_CONFIG) {
  const hits = [];
  for (const c of candidate) {
    if (c.type === "structure") {
      const window = uniqueByItem(recent.filter((r) => r.type === "structure")).slice(0, config.structureWindow);
      const count = window.filter((r) => r.value === c.value).length;
      if (count + 1 > config.structureMaxInWindow) hits.push({ type: "structure", candidate: c.value, previous: c.value, similarity: round((count + 1) / (window.length + 1)) });
      continue;
    }
    if (c.type === "cta") {
      const same = recent.filter((r) => r.type === "cta" && similarity(r.value, c.value) >= 0.8);
      if (same.length >= config.ctaMaxRepeats) hits.push({ type: "cta", candidate: c.value, previous: same[0].value, similarity: 1 });
      continue;
    }
    const threshold = config.thresholds[c.type];
    const comparable = c.type === "hook" || c.type === "phrase" ? ["hook", "phrase"] : [c.type];
    let best = null;
    for (const r of recent) {
      if (!comparable.includes(r.type)) continue;
      const sim = similarity(c.value, r.value);
      if (sim >= threshold && (!best || sim > best.similarity)) best = { type: c.type, candidate: c.value, previous: r.value, similarity: sim };
    }
    if (best) hits.push(best);
  }
  return { repeated: hits.length > 0, hits };
}
function uniqueByItem(fps) {
  const seen = /* @__PURE__ */ new Set();
  return fps.filter((f, i) => {
    const key = f.contentItemId ?? `#${i}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
var TYPE_LABEL = {
  topic: "assunto",
  phrase: "frase",
  metaphor: "met\xE1fora",
  hook: "gancho",
  cta: "CTA",
  structure: "estrutura"
};
function describeAvoidance(report) {
  const types = [...new Set(report.hits.map((h) => h.type))];
  return types.map((t) => `Evitei repetir ${TYPE_LABEL[t]} usado recentemente.`);
}
function avoidanceInstructions(report) {
  if (!report.repeated) return "";
  const lines = report.hits.map((h) => `- ${TYPE_LABEL[h.type]} parecido com algo recente: "${h.previous}"`);
  return `O rascunho anterior repetiu conte\xFAdo recente. Crie OUTRO \xE2ngulo, sem reaproveitar:
${lines.join("\n")}`;
}
function round(n) {
  return Math.round(n * 100) / 100;
}

// ../../packages/domain/src/sync.ts
var SYNC_POLICY = { baseDelayMs: 5e3, maxDelayMs: 30 * 6e4, maxAttempts: 8 };

// ../../packages/domain/src/ai/contract.ts
import { z } from "npm:zod@4";
var PROMPT_VERSION = "content-v1.3.0";
var NARRATIVE_STRUCTURES = ["confissao", "pergunta", "contraste", "historia", "conselho", "observacao"];
var PLATFORMS = ["instagram", "tiktok", "facebook", "youtube_shorts"];
var text = (min = 1, max = 2e3) => z.string().trim().min(min).max(max);
var ContentDraftSchema = z.object({
  title: text(3, 120),
  pillar: text(2, 60),
  format: z.enum(["thought", "main_video", "story", "broll"]),
  duration_seconds: z.number().int().min(3).max(180),
  structure: z.enum(NARRATIVE_STRUCTURES),
  topic: text(3, 200),
  key_phrase: text(3, 300),
  metaphor: z.string().trim().max(200),
  hook_options: z.array(text(3, 200)).length(3),
  narrative: z.object({ e: text(3, 800), mas: text(3, 800), por_isso: text(3, 800) }),
  script: text(10, 4e3),
  screen_text: z.string().trim().max(120),
  cta: text(2, 200),
  caption: z.object({
    instagram: text(3, 2200),
    tiktok: text(3, 2200),
    facebook: text(3, 5e3),
    youtube_shorts: text(3, 5e3)
  }),
  hashtags: z.array(z.string().trim().regex(/^#[\p{L}\p{N}_]+$/u)).min(1).max(15),
  recording_suggestions: z.array(z.object({ scene: text(2, 200), duration_seconds: z.number().int().min(1).max(60), location_hint: z.string().trim().max(200) })).min(1).max(8),
  versions: z.array(z.object({ duration_seconds: z.number().int().min(5).max(180), script: text(5, 4e3) })).max(4)
});
var GenerateRequestSchema = z.object({
  workspace_id: z.uuid(),
  content_item_id: z.uuid().nullable(),
  format: z.enum(["thought", "main_video"]),
  pillar_slug: text(2, 60),
  event_text: z.string().trim().max(1500).nullable(),
  /** project briefing from the studio (mode, filmed SKU, ice-cream source, recipe) — optional */
  brief: z.string().trim().max(1500).nullable().optional()
});
function parseDraft(input) {
  const r = ContentDraftSchema.safeParse(input);
  if (r.success) return { ok: true, draft: r.data };
  return { ok: false, errors: r.error.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`) };
}
var STRIP_KEYS = /* @__PURE__ */ new Set(["$schema", "minItems", "maxItems", "minLength", "maxLength", "minimum", "maximum", "pattern", "format"]);
function contentDraftJsonSchema() {
  const raw = z.toJSONSchema(ContentDraftSchema, { target: "draft-7" });
  return strip(raw);
}
function strip(node) {
  if (Array.isArray(node)) return node.map(strip);
  if (node && typeof node === "object") {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      if (STRIP_KEYS.has(k)) continue;
      out[k] = strip(v);
    }
    if (out.type === "object") out.additionalProperties = false;
    return out;
  }
  return node;
}

// ../../packages/domain/src/ai/prompt.ts
var RODRIGO_PROFILE = {
  displayName: "Rodrigo Serra",
  handle: "RodrigoSerra.me",
  positioning: "Vida real, evolu\xE7\xE3o pessoal e reflex\xF5es de um homem 40+.",
  signature: "RodrigoSerra.me",
  closingPhrase: "E se der certo!",
  voiceRules: [
    "humano, pr\xF3ximo, simples, direto e esperan\xE7oso",
    "fala com UMA pessoa, nunca com uma plateia",
    "nunca soa como guru ou coach gen\xE9rico",
    "evita jarg\xE3o motivacional (ex.: 'saia da zona de conforto', 'mindset', 'voc\xEA \xE9 incr\xEDvel')",
    "exemplos concretos do dia a dia, n\xE3o abstra\xE7\xF5es"
  ]
};
var VIRAL_FORMATS = [
  "\u201Cningu\xE9m te conta que\u2026\u201D (revela algo que todo mundo vive e ningu\xE9m fala)",
  "\u201Ceu costumava\u2026 hoje eu\u2026\u201D (antes e depois pessoal)",
  "\u201Co erro que eu cometi com\u2026\u201D (confiss\xE3o com aprendizado)",
  "pergunta direta que o espectador responde na cabe\xE7a (\u201Cquando foi a \xFAltima vez que voc\xEA\u2026?\u201D)",
  "contraste: o que todo mundo pensa \xD7 o que acontece de verdade",
  "cena concreta do dia (lugar, hora, frase ouvida) que vira li\xE7\xE3o",
  "lista curta de 3 (\u201C3 coisas que\u2026\u201D), s\xF3 no v\xEDdeo principal"
];
var DURATION_RANGE = {
  thought: [5, 15],
  main_video: [45, 120]
};
var BUSINESS_MAIN_RANGE = [30, 90];
function buildPrompt(input) {
  const b = input.profile.kind === "empresa" ? input.profile.business : void 0;
  const [min, max] = b && input.format === "main_video" ? BUSINESS_MAIN_RANGE : DURATION_RANGE[input.format];
  const system = b ? businessSystem(input.profile, b) : [
    `Voc\xEA \xE9 o roteirista pessoal de ${input.profile.displayName} (${input.profile.handle}). Posicionamento: ${input.profile.positioning}`,
    `Voz: ${input.profile.voiceRules.join("; ")}.`,
    "Escreva em portugu\xEAs do Brasil, como fala, frases curtas, sem emojis no roteiro.",
    "Estrutura narrativa obrigat\xF3ria: E (situa\xE7\xE3o real) -> MAS (tens\xE3o/virada) -> POR ISSO (aprendizado/a\xE7\xE3o).",
    `O roteiro TERMINA exatamente com a frase de fechamento: "${input.profile.closingPhrase}" \u2014 n\xE3o altere essa frase.`,
    `As legendas terminam com a assinatura ${input.profile.signature}.`,
    "Nunca prometa viraliza\xE7\xE3o, resultado garantido ou n\xFAmeros de alcance.",
    "D\xEA 3 ganchos diferentes entre si (formas diferentes: pergunta, confiss\xE3o, contraste...).",
    "Regras de reten\xE7\xE3o para v\xEDdeo curto (Reels/TikTok/Shorts):",
    "- o gancho prende nos 2 primeiros segundos: at\xE9 12 palavras, concreto, abre uma lacuna de curiosidade ou quebra uma expectativa;",
    "- uma \xFAnica ideia por v\xEDdeo, com um detalhe espec\xEDfico e real (lugar, hora, objeto, frase ouvida) em vez de abstra\xE7\xE3o;",
    "- tens\xE3o no MAS: algo que o espectador tamb\xE9m vive e n\xE3o admite;",
    "- o POR ISSO entrega uma virada pr\xE1tica que d\xE1 vontade de salvar ou mandar para algu\xE9m;",
    "- a 1\xAA frase j\xE1 diz o assunto com a palavra que algu\xE9m pesquisaria (a plataforma transcreve a fala e usa na busca); nada de 'oi, gente' nem contexto antes do gancho;",
    "- o que mais espalha \xE9 algu\xE9m MANDAR o v\xEDdeo para outra pessoa: escreva pensando em quem vai receber;",
    "- o CTA \xE9 UM destes, o que combinar: pedir para mandar para algu\xE9m espec\xEDfico ('manda para quem\u2026') ou uma pergunta simples para responder nos coment\xE1rios, ligada ao tema (nada de 'curte e compartilha');",
    "- screen_text: 2 a 5 palavras que resumem o v\xEDdeo sem repetir o gancho;",
    "- legendas por plataforma adaptadas (TikTok curta e direta; Instagram com respiro; YouTube Shorts com t\xEDtulo forte);",
    "Formato que viraliza (escolha UM que combine com o tema e use de verdade, sem for\xE7ar):",
    ...VIRAL_FORMATS.map((f) => `- ${f};`),
    "Coer\xEAncia (o texto \xE9 lido em voz alta, parte por parte, e precisa fazer sentido para quem nunca viu o perfil):",
    "- uma ideia s\xF3, do come\xE7o ao fim; cada frase continua a anterior (nada de frases soltas de efeito, colcha de retalhos ou prov\xE9rbio gen\xE9rico);",
    "- o gancho promete algo e o final entrega exatamente isso; o tema do dia (pilar) \xE9 o assunto, n\xE3o um detalhe;",
    "- nada de met\xE1fora confusa nem palavra dif\xEDcil; se uma frase n\xE3o d\xE1 para entender de primeira, reescreva;",
    "- antes de responder, leia o roteiro inteiro em voz alta mentalmente: se algum trecho n\xE3o se liga ao resto, corte.",
    "Responda somente no JSON do schema."
  ].join("\n");
  const user = [
    b ? `Pilar de venda: ${input.pillarName}. Antes de escrever, decida (coerentes entre si): p\xFAblico, n\xEDvel de consci\xEAncia, UMA dor, UMA obje\xE7\xE3o, UM desejo, UMA prova visual, UMA emo\xE7\xE3o e a a\xE7\xE3o esperada. Sem isso, n\xE3o escreva.` : "",
    `Formato: ${input.format === "thought" ? "Pensamento do Dia" : "V\xEDdeo principal"} (${min}\u2013${max}s).`,
    b ? "" : `Pilar editorial: ${input.pillarName}.`,
    input.eventText ? `${b ? "Situa\xE7\xE3o real da empresa hoje" : "Acontecimento real de hoje contado pelo criador"} (transforme em conte\xFAdo, preserve os fatos): "${input.eventText}"` : b ? "Sem acontecimento espec\xEDfico: parta de uma dor real do cliente." : "Sem acontecimento espec\xEDfico: parta de uma situa\xE7\xE3o comum e concreta do dia dele.",
    input.brief ? `Briefing do projeto (siga \xE0 risca; dados do equipamento s\xF3 os daqui): ${input.brief}` : "",
    input.format === "main_video" ? "Inclua em 'versions' varia\xE7\xF5es de 15s, 30s e 60s quando fizer sentido." : "Pensamento do Dia: 3 a 5 frases curtas no 'script'. A 1\xAA frase \xC9 o gancho (at\xE9 12 palavras; \xE9 gravada sozinha como 'Gancho'); as do meio desenvolvem UMA ideia; a \xFAltima antes do fechamento \xE9 a virada que d\xE1 vontade de mandar para algu\xE9m. Em 'versions' inclua no m\xE1ximo uma varia\xE7\xE3o de at\xE9 15s.",
    input.recentSummaries.length ? `Conte\xFAdos recentes (n\xE3o repita assunto, frase, met\xE1fora, gancho, CTA nem estrutura):
${input.recentSummaries.map((s) => `- ${s}`).join("\n")}` : "",
    input.avoid
  ].filter(Boolean).join("\n\n");
  return { system, user, promptVersion: PROMPT_VERSION };
}
function businessSystem(profile, b) {
  const list = (xs) => xs.map((x) => `- ${x}`).join("\n");
  return [
    `Voc\xEA \xE9 o roteirista de v\xEDdeos de venda da ${b.brand} (${b.product}). Posicionamento: ${profile.positioning}`,
    `Quem compra \xE9 empres\xE1rio: algu\xE9m que ${b.audience}. N\xE3o \xE9 consumidor final.`,
    `Voz: ${profile.voiceRules.join("; ")}.`,
    "Pergunta central de todo v\xEDdeo: o que impede esse empres\xE1rio de comprar hoje? O v\xEDdeo elimina UMA d\xFAvida e mostra UMA prova.",
    "Mapeie a estrutura assim: E = a dor real do cliente (concreta, do dia a dia da opera\xE7\xE3o); MAS = a obje\xE7\xE3o ou a cren\xE7a errada, respondida sem enrolar; POR ISSO = a prova visual + o diferencial que resolve.",
    "O tipo de v\xEDdeo segue o pilar: Educa\xE7\xE3o = erro comum e como escolher; Autoridade = experi\xEAncia e f\xE1brica; Demonstra\xE7\xE3o = produto em uso com prova; Bastidores = produ\xE7\xE3o/qualidade; Comparativo = 'parece igual, mas n\xE3o \xE9'; Hist\xF3rias = caso real de cliente; Oferta = condi\xE7\xE3o e escassez REAIS, sem inventar.",
    b.noPrice ? "PROIBIDO falar pre\xE7o, valor, parcela, desconto em n\xFAmero ou 'R$' \u2014 nem no roteiro, nem na tela, nem nas legendas. Pre\xE7o \xE9 no atendimento." : "",
    "Nunca invente especifica\xE7\xE3o t\xE9cnica, n\xFAmero ou depoimento que n\xE3o esteja abaixo.",
    `Dores reais:
${list(b.pains)}`,
    `Desejos:
${list(b.desires)}`,
    `Obje\xE7\xF5es e respostas (use UMA por v\xEDdeo):
${b.objections.map((o) => `- "${o.objection}" \u2192 ${o.answer}`).join("\n")}`,
    `Provas visuais que d\xE1 para filmar (use em recording_suggestions):
${list(b.proofs)}`,
    `Diferenciais comprovados (pode afirmar):
${list(b.differentiators)}`,
    b.pendingClaims?.length ? `Alega\xE7\xF5es AINDA SEM PROVA \u2014 N\xC3O afirme nem cite n\xFAmeros delas:
${list(b.pendingClaims)}` : "",
    `CTAs poss\xEDveis (adapte, sem press\xE3o):
${list(b.ctas)}`,
    `As legendas terminam com a assinatura ${profile.signature}.`,
    "Gancho de at\xE9 12 palavras que para o scroll (dor financeira, curiosidade, compara\xE7\xE3o, autoridade ou erro). screen_text de 2 a 5 palavras.",
    "Legendas por plataforma adaptadas; no Facebook/Marketplace pode detalhar o uso do produto (sem pre\xE7o).",
    "Responda somente no JSON do schema."
  ].filter(Boolean).join("\n");
}
var PLATFORM_LIMITS = { instagram: 2200, tiktok: 2200, facebook: 5e3, youtube_shorts: 5e3 };
function finalizeDraft(draft, profile) {
  const closing = profile.closingPhrase.trim();
  const withClosing = (script) => {
    let body = script.trim();
    const idx = body.toLowerCase().lastIndexOf(closing.toLowerCase().replace(/[!.]+$/, ""));
    if (idx >= 0 && body.length - idx <= closing.length + 2) body = body.slice(0, idx).trim();
    return closing ? `${body}

${closing}` : body;
  };
  const tags = draft.hashtags.join(" ");
  const caption = {};
  for (const p of PLATFORMS) {
    let c = draft.caption[p].trim();
    if (!c.includes(profile.signature)) c = `${c}

${profile.signature}`;
    if ((p === "instagram" || p === "tiktok") && !c.includes(draft.hashtags[0] ?? "#")) c = `${c}

${tags}`;
    caption[p] = c.slice(0, PLATFORM_LIMITS[p]);
  }
  return {
    ...draft,
    script: withClosing(draft.script),
    versions: draft.versions.map((v) => ({ ...v, script: withClosing(v.script) })),
    caption
  };
}
function summarizeForMemory(d) {
  return [d.topic, `frase: "${d.key_phrase}"`, d.metaphor ? `met\xE1fora: ${d.metaphor}` : "", `CTA: ${d.cta}`, `estrutura: ${d.structure}`].filter(Boolean).join(" | ");
}

// ../../packages/domain/src/profiles.ts
var BUSINESS_PILLARS = [
  { slug: "educacao", name: "Educa\xE7\xE3o (erros e como escolher)", targetPercent: 30 },
  { slug: "autoridade", name: "Autoridade (experi\xEAncia e f\xE1brica)", targetPercent: 20 },
  { slug: "demonstracao", name: "Demonstra\xE7\xE3o (produto em uso)", targetPercent: 15 },
  { slug: "bastidores", name: "Bastidores", targetPercent: 10 },
  { slug: "comparativo", name: "Comparativo (parece igual, n\xE3o \xE9)", targetPercent: 10 },
  { slug: "historias", name: "Hist\xF3rias de cliente", targetPercent: 10 },
  { slug: "oferta", name: "Oferta (sem falar pre\xE7o)", targetPercent: 5 }
];
var CONTROLPOT_STRATEGY = {
  brand: "ControlPot",
  product: "mixer profissional de milk-shake",
  audience: "tem a\xE7aiteria, sorveteria, cafeteria ou franquia",
  pains: [
    "o milk-shake sai aguado em alguns dias",
    "cada funcion\xE1rio faz o milk-shake de um jeito",
    "a m\xE1quina perde pot\xEAncia bem no hor\xE1rio de pico",
    "a m\xE1quina quebra e a opera\xE7\xE3o para",
    "a assist\xEAncia demora e n\xE3o acha pe\xE7a",
    "o cliente prova uma vez e n\xE3o volta"
  ],
  desires: [
    "milk-shake cremoso igual todo dia",
    "atender r\xE1pido no pico sem dor de cabe\xE7a",
    "equipamento profissional que passa confian\xE7a",
    "suporte quando precisar"
  ],
  objections: [
    { objection: "Est\xE1 caro", answer: "Barato que para no pico sai caro: cada hora parada \xE9 venda perdida e cliente que n\xE3o volta." },
    { objection: "Outra marca \xE9 mais barata", answer: "Compara o resultado no copo e quanto tempo ela aguenta trabalhando todo dia, n\xE3o s\xF3 a etiqueta." },
    { objection: "E se quebrar?", answer: "Tem assist\xEAncia t\xE9cnica pr\xF3pria e pe\xE7a de reposi\xE7\xE3o, ent\xE3o a opera\xE7\xE3o n\xE3o fica parada esperando." },
    { objection: "Posso bater direto no copo?", answer: "Pode: d\xE1 para bater direto no copo pl\xE1stico, sem sujar outra caneca." },
    { objection: "Qual a diferen\xE7a pra uma comum?", answer: "N\xE3o precisa acreditar em mim: olha a textura no copo, lado a lado." }
  ],
  proofs: [
    "close na textura cremosa escorrendo no copo inclinado",
    "m\xE1quina batendo por 20 segundos",
    "close da caneca c\xF4nica",
    "funcion\xE1rio preparando no balc\xE3o",
    "compara\xE7\xE3o lado a lado: aguado x cremoso",
    "linha de produ\xE7\xE3o e teste de qualidade",
    "assist\xEAncia t\xE9cnica trabalhando"
  ],
  // claims with a number or a third-party name need proof before they go on video (briefing MMIX, item 2)
  differentiators: [
    "fabrica\xE7\xE3o pr\xF3pria em Londrina/PR",
    "assist\xEAncia t\xE9cnica pr\xF3pria"
  ],
  pendingClaims: [
    "mais de 20 anos de mercado",
    "mais de 4.000 m\xE1quinas em opera\xE7\xE3o",
    "caneca c\xF4nica exclusiva e o resultado dela na textura",
    "atende grandes redes e franquias"
  ],
  ctas: [
    "Fala com um especialista e v\xEA qual modelo combina com a sua opera\xE7\xE3o.",
    "Conhe\xE7a a linha completa e tira sua d\xFAvida com a nossa equipe.",
    "Me conta nos coment\xE1rios: como \xE9 o milk-shake a\xED na sua opera\xE7\xE3o?",
    "Solicita um or\xE7amento e compara na pr\xE1tica."
  ],
  noPrice: true
};
var CONTROLPOT_PROFILE = {
  displayName: "ControlPot",
  handle: "ControlPot",
  positioning: "Mixers profissionais para quem vive de milk-shake: resultado igual todo dia e opera\xE7\xE3o que n\xE3o para.",
  signature: "ControlPot",
  closingPhrase: "",
  voiceRules: [
    "fala de empres\xE1rio para empres\xE1rio, direto e pr\xE1tico",
    "uma obje\xE7\xE3o por v\xEDdeo, nunca v\xE1rias",
    "mostra prova, n\xE3o promete",
    "nunca fala pre\xE7o nem valor",
    "sem exagero e sem termos gen\xE9ricos de propaganda"
  ],
  kind: "empresa",
  business: CONTROLPOT_STRATEGY
};
var BUSINESS_WEEKDAY_BLOCKS = [
  { startTime: "11:00", title: "V\xEDdeo de venda (produto)", contentHint: "gancho, prova e chamada \u2014 30\u201360s", optional: false, format: "main_video" },
  { startTime: "14:30", title: "Prova visual / B-roll do produto", contentHint: "textura, m\xE1quina em uso, bastidor", optional: false, format: "broll" }
];
function businessRoutine(newId) {
  const blocks = [];
  for (let weekday = 1; weekday <= 5; weekday++) for (const b of BUSINESS_WEEKDAY_BLOCKS) blocks.push({ ...b, id: newId(), weekday });
  return blocks;
}
var PROFILE_TEMPLATES = [
  {
    id: "pessoal-rodrigo",
    label: "Pessoal \u2014 RodrigoSerra.me",
    description: 'Reflex\xE3o, vida real, academia e fam\xEDlia. Fecha com "E se der certo!".',
    name: "RodrigoSerra.me",
    profile: { ...RODRIGO_PROFILE, kind: "pessoal" },
    pillars: RODRIGO_PILLARS.map((p) => ({ ...p })),
    routine: rodrigoRoutine
  },
  {
    id: "empresa-controlpot",
    label: "Empresa \u2014 ControlPot",
    description: "V\xEDdeos que vendem mixer para empres\xE1rio: dor, obje\xE7\xE3o, prova e chamada. Nunca fala pre\xE7o.",
    name: "ControlPot",
    profile: CONTROLPOT_PROFILE,
    pillars: BUSINESS_PILLARS.map((p) => ({ ...p })),
    routine: businessRoutine
  },
  {
    id: "empresa-nova",
    label: "Outra empresa / produto",
    description: "Mesma estrat\xE9gia de venda; depois voc\xEA troca produto, dores e obje\xE7\xF5es.",
    name: "Minha empresa",
    profile: {
      ...CONTROLPOT_PROFILE,
      displayName: "Minha empresa",
      handle: "Minha empresa",
      signature: "Minha empresa",
      positioning: "Produto que resolve um problema real do meu cliente.",
      business: {
        brand: "Minha empresa",
        product: "meu produto",
        audience: "precisa resolver esse problema",
        pains: ["perde tempo com um processo que d\xE1 errado", "gasta duas vezes porque comprou o errado"],
        desires: ["resultado igual todo dia", "comprar uma vez e ficar tranquilo"],
        objections: [{ objection: "Est\xE1 caro", answer: "O barato que d\xE1 problema sai mais caro no fim do m\xEAs." }, { objection: "E se der problema?", answer: "A gente d\xE1 suporte e resolve r\xE1pido." }],
        proofs: ["produto em uso", "close no resultado", "cliente usando"],
        differentiators: ["atendimento de verdade"],
        ctas: ["Me chama e tira sua d\xFAvida.", "Conta nos coment\xE1rios como \xE9 a\xED com voc\xEA."],
        noPrice: true
      }
    },
    pillars: BUSINESS_PILLARS.map((p) => ({ ...p })),
    routine: businessRoutine
  }
];
var PRICE = /R\$\s*\d|\b\d+(?:[.,]\d+)?\s*reais\b|\bpre[çc]os?\b|\bparcela(?:s|do|mento)?\b|\bs[óo] \d|\b\d+\s*%\s*(?:off|de desconto)|\bdesconto de \d|\bcusta(?:m)? (?:s[óo] |apenas |a partir de )?\d/i;
function mentionsPrice(d) {
  const texts = [d.script, d.cta, d.screen_text, ...d.hook_options, ...Object.values(d.caption), ...d.versions.map((v) => v.script)];
  return texts.some((t) => PRICE.test(t));
}

// ../../packages/domain/src/studio.ts
function pendingClaimsIn(text2, pendingClaims) {
  const t = norm(text2);
  const hits = pendingClaims.filter((c) => {
    const words = norm(c).split(" ").filter((w) => w.length > 3 || /\d/.test(w));
    const key = words.filter((w) => /\d/.test(w));
    if (key.length) return key.some((k) => t.includes(k.replace(/\./g, "")) || t.includes(k));
    const found = words.filter((w) => t.includes(w)).length;
    return found >= 2 && found / words.length >= 0.5;
  });
  return hits;
}
var norm = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9. ]/g, " ").replace(/\s+/g, " ").trim();

// ../../packages/domain/src/music.ts
var mk = (id, mood, title, artist, sha256, durationSec) => ({ id: `mixkit-${id}`, mood, title, artist, url: `https://assets.mixkit.co/music/${id}/${id}.mp3`, sha256, durationSec });
var MUSIC_LIBRARY = [
  mk(22, "reflexao", "Piano Reflections", "Ahjay Stelino", "7d58c4255d91f58e29e61520b6011cabd5a54b3e89b54646cebac9d37295bbec", 199),
  mk(601, "reflexao", "Skyline", "Eugenio Mininni", "2fcb36e7e58c4b6bc1505b7980237fdad86696589572a958bb6ee2084c592cc5", 206),
  mk(599, "reflexao", "Possible Dreams", "Eugenio Mininni", "ee6d055c20cccda716b6b63a154ef0dc825195b7061dc439abb8a623973f4798", 159),
  mk(32, "motivacional", "Driving Ambition", "Ahjay Stelino", "e3c88488e65b8c87a6f06120983ce2cb12ea3aeba99f8cadb7ee5d6d284ef2c6", 102),
  mk(31, "motivacional", "Dreaming Big", "Ahjay Stelino", "8c89819547b42a80750fb25f37a960a1f45f6fd66bc8d784ac817b98b002897c", 110),
  mk(34, "motivacional", "Raising Me Higher", "Ahjay Stelino", "619b82cea299230cca5beac36d049291a1cb2be8ce0afdafda3e06fb30d06525", 98),
  mk(1183, "treino", "Karma", "Michael Ramir C.", "56f331c37552486a1a31c65a443f1669ed37f7fb3bd99d9078d23ec55caa052f", 135),
  mk(470, "treino", "Golden Storm", "Diego Nava", "32e5a363ce84f0b633579d0b10cf3c758ae3c02f5121147a321e2483e3384e26", 95),
  mk(1e3, "treino", "I Can Hear Your Heartbeat", "Michael Ramir C.", "a23c959605dc4a53f7e3b8c8949fcc0d082c29989b944bb2a7f8d9601ddca0d1", 110),
  mk(839, "familia", "Tears of Joy", "Michael Ramir C.", "30717c4e8d2a954a6163477b831e5b8981b406d2c34d72820fce4d40a8686ddc", 140),
  mk(963, "familia", "Just Keep Walking", "Michael Ramir C.", "fa93f4808cecc643eee8d74647bd8b823991f2155672b7d37f3db79f9beb7e16", 125),
  mk(801, "familia", "Happy Home", "Michael Ramir C.", "76b82159ba1d6821a5ac9465e8ff19007446c1b657dfe53b5917fc8896b3bf21", 110),
  mk(2, "humor", "Comical", "Ahjay Stelino", "2f5ed23f2c51b5aa28b237563ee1249d12094fefce7afdaddee4f5a330e010cb", 114),
  mk(466, "humor", "Games Worldbeat", "Bernardo R.", "a1c70e5719bdfbe5dd8ec064939b27e3baed8c2b7f9375ae5b361e6ba71d4922", 107),
  mk(474, "empresa", "What About Action?", "Diego Nava", "4bcd99a13f3d71c6d356c2459f6f585f0d3f91ca8912aeef81ac626b8c8e3133", 117),
  mk(729, "empresa", "Pop Track 03", "Lily J", "0bb90793c71a07e6d698afdd434b32ffb4fe93dbbdb0577d3e71a4de80b0337b", 97),
  mk(1167, "empresa", "Close Up", "Michael Ramir C.", "a7f05a29d07a84d38072ccd2b35204bca812db86e75b2a837e71cc144d3e739b", 95),
  mk(441, "calmo", "Meditation", "Arulo", "6ffb81be8ab2447eb7b9357d6ae3d1b58eb8bc85376a724fafa5fe4d1acf562a", 118),
  mk(175, "calmo", "Digital Clouds", "Alejandro Maga\xF1a (A. M.)", "71cd4ea39edcc7532672bd97311abadfd318d00e7a828310a88b4f57fad9cd48", 101)
];

// src/edge.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2";

// src/adapters.ts
import { createClient } from "npm:@supabase/supabase-js@2";
function geminiClient(apiKey, model, fetchImpl = fetch) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;
  let keyInQuery = false;
  async function send(body) {
    const target = keyInQuery ? `${url}?key=${encodeURIComponent(apiKey)}` : url;
    const headers = { "Content-Type": "application/json" };
    if (!keyInQuery) headers["x-goog-api-key"] = apiKey;
    const res = await fetchImpl(target, { method: "POST", headers, body: JSON.stringify(body) });
    return { res, json: await res.json().catch(() => ({})) };
  }
  async function call(body) {
    let r = await send(body);
    if ((r.res.status === 401 || r.res.status === 403) && !keyInQuery) {
      keyInQuery = true;
      r = await send(body);
    }
    return r;
  }
  return {
    model,
    source: "gemini",
    async complete({ system, user, schema }) {
      const base = { systemInstruction: { parts: [{ text: system }] }, contents: [{ role: "user", parts: [{ text: user }] }] };
      let r = await call({ ...base, generationConfig: { temperature: 0.9, responseMimeType: "application/json", responseJsonSchema: schema } });
      if (r.res.status === 400) r = await call({ ...base, generationConfig: { temperature: 0.9, responseMimeType: "application/json" } });
      if (!r.res.ok) throw new Error(`gemini HTTP ${r.res.status} ${r.json.error?.status ?? ""}: ${r.json.error?.message ?? ""}`.slice(0, 300));
      const text2 = r.json.candidates?.[0]?.content?.parts?.map((p) => p.text ?? "").join("") ?? "";
      if (!text2) throw new Error("empty gemini response");
      return JSON.parse(text2.replace(/^```(?:json)?\s*|\s*```$/g, ""));
    }
  };
}
function userSupabase(url, anonKey, accessToken) {
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${accessToken}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var MEMORY_WINDOW = 120;
function supabaseMemory(db, userId) {
  return {
    async canWrite(ws) {
      const { data, error } = await db.rpc("can_write_workspace", { ws });
      if (error) throw error;
      return data === true;
    },
    async profile(ws) {
      const { data, error } = await db.from("creator_profiles").select("*").eq("workspace_id", ws).maybeSingle();
      if (error) throw error;
      if (!data) throw Object.assign(new Error("workspace not found"), { status: 404 });
      return {
        displayName: data.display_name,
        handle: data.handle ?? data.display_name,
        positioning: data.positioning ?? "",
        signature: data.signature ?? data.handle ?? "",
        closingPhrase: data.closing_phrase ?? "",
        voiceRules: data.voice_rules?.length ? data.voice_rules : RODRIGO_PROFILE.voiceRules,
        // kind + sales strategy of a business profile live in creator_profiles.tone
        kind: data.tone?.kind === "empresa" ? "empresa" : "pessoal",
        business: data.tone?.kind === "empresa" ? data.tone.business : void 0
      };
    },
    async pillarName(ws, slug) {
      const { data } = await db.from("content_pillars").select("name").eq("workspace_id", ws).eq("slug", slug).maybeSingle();
      return data?.name ?? slug;
    },
    async recentFingerprints(ws) {
      const { data, error } = await db.from("content_fingerprints").select("fingerprint_type, fingerprint, content_item_id, created_at").eq("workspace_id", ws).order("created_at", { ascending: false }).limit(MEMORY_WINDOW);
      if (error) throw error;
      return (data ?? []).map((r) => ({ type: r.fingerprint_type, value: r.fingerprint, contentItemId: r.content_item_id, createdAt: r.created_at }));
    },
    async recentSummaries(ws) {
      const { data } = await db.from("scripts").select("draft").eq("workspace_id", ws).order("created_at", { ascending: false }).limit(10);
      return (data ?? []).filter((r) => r.draft?.topic).map((r) => summarizeForMemory(r.draft));
    },
    async saveRun(run) {
      const { error } = await db.from("generation_runs").insert({
        workspace_id: run.workspaceId,
        content_item_id: null,
        source: run.model.startsWith("gemini") ? "gemini" : "openai",
        model: run.model,
        prompt_version: run.promptVersion,
        request: run.request,
        response: run.response,
        accepted: run.accepted,
        rejection_reason: run.rejectionReason,
        repetition: run.repetition ?? {},
        latency_ms: run.latencyMs,
        created_by: userId
      });
      if (error) console.warn(JSON.stringify({ level: "warn", msg: "generation_run not saved", code: error.code }));
    }
  };
}

// src/generation.service.ts
var LlmUnavailableError = class extends Error {
};
var MAX_ATTEMPTS = 3;
async function generateContent(req, llm, memory) {
  if (!await memory.canWrite(req.workspace_id)) throw Object.assign(new Error("forbidden"), { status: 403 });
  const [profile, pillarName, recent, summaries] = await Promise.all([
    memory.profile(req.workspace_id),
    memory.pillarName(req.workspace_id, req.pillar_slug),
    memory.recentFingerprints(req.workspace_id),
    memory.recentSummaries(req.workspace_id)
  ]);
  const schema = contentDraftJsonSchema();
  let avoid = "";
  const avoided = [];
  let fallback = null;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const prompt = buildPrompt({ profile, pillarName, format: req.format, eventText: req.event_text, brief: req.brief ?? null, recentSummaries: summaries, avoid });
    const started = Date.now();
    let raw;
    try {
      raw = await llm.complete({ system: prompt.system, user: prompt.user, schema });
    } catch (e) {
      throw new LlmUnavailableError(e instanceof Error ? e.message : "llm error");
    }
    const base = { workspaceId: req.workspace_id, contentItemId: req.content_item_id, model: llm.model, promptVersion: prompt.promptVersion, request: { ...req, attempt }, response: raw, latencyMs: Date.now() - started };
    const parsed = parseDraft(raw);
    if (!parsed.ok) {
      await memory.saveRun({ ...base, accepted: false, rejectionReason: `schema: ${parsed.errors.slice(0, 5).join("; ")}`, repetition: null });
      continue;
    }
    const draft = finalizeDraft(parsed.draft, profile);
    if (profile.business?.noPrice && profile.kind === "empresa" && mentionsPrice(draft)) {
      await memory.saveRun({ ...base, accepted: false, rejectionReason: "price", repetition: null });
      avoid = "A vers\xE3o anterior falou pre\xE7o/valor/parcela. PROIBIDO: reescreva sem nenhum pre\xE7o.";
      continue;
    }
    const unproven = profile.kind === "empresa" ? pendingClaimsIn([draft.script, draft.cta, ...draft.hook_options].join(" "), profile.business?.pendingClaims ?? []) : [];
    if (unproven.length) {
      await memory.saveRun({ ...base, accepted: false, rejectionReason: "claim_sem_prova", repetition: null });
      avoid = `A vers\xE3o anterior afirmou alega\xE7\xE3o SEM PROVA (${unproven.join("; ")}). Reescreva sem ela e sem n\xFAmeros n\xE3o comprovados.`;
      continue;
    }
    const report = checkRepetition(fingerprintsFor(draft), recent);
    if (report.repeated) {
      await memory.saveRun({ ...base, accepted: false, rejectionReason: "repetition", repetition: report });
      avoided.push(...describeAvoidance(report));
      avoid = avoidanceInstructions(report);
      if (!fallback || report.hits.length < fallback.report.hits.length) fallback = { draft, report };
      continue;
    }
    await memory.saveRun({ ...base, accepted: true, rejectionReason: null, repetition: report });
    return respond(draft, llm, attempt, avoided, []);
  }
  if (fallback) {
    return respond(fallback.draft, llm, MAX_ATTEMPTS, avoided, ["N\xE3o consegui um \xE2ngulo 100% in\xE9dito; revise o texto antes de gravar."]);
  }
  throw new LlmUnavailableError("A IA n\xE3o retornou um roteiro v\xE1lido.");
}
function respond(draft, llm, attempts, avoided, extra) {
  const model = llm.model;
  const unique = [...new Set(avoided)];
  return {
    draft,
    fingerprints: fingerprintsFor(draft),
    meta: { source: llm.source ?? "openai", model, prompt_version: PROMPT_VERSION, attempts, avoided: unique },
    notices: [...unique, ...extra]
  };
}

// src/edge.ts
var json = (status, body) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
Deno.serve(async (req) => {
  if (req.method !== "POST") return json(405, { code: "method_not_allowed" });
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? req.headers.get("apikey") ?? "";
  const key = Deno.env.get("GEMINI_API_KEY");
  const token = /^Bearer (.+)$/.exec(req.headers.get("Authorization") ?? "")?.[1];
  if (!token) return json(401, { code: "unauthorized" });
  const { data, error } = await createClient2(url, anon, { auth: { persistSession: false } }).auth.getUser(token);
  if (error || !data.user) return json(401, { code: "unauthorized" });
  const parsed = GenerateRequestSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) return json(400, { code: "invalid_request" });
  if (!key) return json(503, { code: "llm_not_configured" });
  try {
    const llm = geminiClient(key, Deno.env.get("GEMINI_MODEL") ?? "gemini-flash-latest");
    return json(200, await generateContent(parsed.data, llm, supabaseMemory(userSupabase(url, anon, token), data.user.id)));
  } catch (e) {
    const status = e.status;
    if (status === 403 || status === 404) return json(404, { code: "workspace_not_found" });
    if (e instanceof LlmUnavailableError) {
      console.error(JSON.stringify({ msg: "generate.llm_unavailable", error: e.message.replaceAll(key, "***") }));
      return json(502, { code: "llm_unavailable" });
    }
    console.error(JSON.stringify({ msg: "generate.failed", error: e instanceof Error ? e.message : String(e) }));
    return json(500, { code: "internal_error" });
  }
});
