// GENERATED by apps/api build:edge — do not edit

// ../../packages/domain/src/repetition.ts
var DEFAULT_REPETITION_CONFIG = {
  thresholds: { topic: 0.5, phrase: 0.45, metaphor: 0.5, hook: 0.5 },
  ctaMaxRepeats: 2,
  structureMaxInWindow: 3,
  structureWindow: 5
};
var STOPWORDS = new Set(
  "a o as os um uma uns umas de da do das dos em na no nas nos por para pra pro com sem e ou que se me te nos voce voces eu ele ela eles elas isso isto esse essa este esta aquilo mais menos muito muita ja nao sim so ao aos \xE0 \xE0s \xE9 era ser foi vai vou ter tem tinha sua seu suas seus minha meu minhas meus tua teu como quando onde porque pq mas entao ent\xE3o hoje".split(
    " "
  ).map((w) => stripAccents(w))
);
function stripAccents(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "");
}
function normalizeText(s) {
  return stripAccents(s.toLowerCase()).replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();
}
function stem(w) {
  return w.length > 4 ? w.replace(/(mente|coes|cao|oes|ais|eis|res|es|as|os|s)$/u, "") : w;
}
function contentTokens(s) {
  return normalizeText(s).split(" ").filter((w) => w.length > 1 && !STOPWORDS.has(w)).map(stem);
}
function similarity(a, b) {
  const ta = contentTokens(a);
  const tb = contentTokens(b);
  if (ta.length === 0 || tb.length === 0) return 0;
  const uni = jaccard(new Set(ta), new Set(tb));
  const bi = jaccard(bigrams(ta), bigrams(tb));
  const small = ta.length <= tb.length ? ta : tb;
  const big = new Set(ta.length <= tb.length ? tb : ta);
  const containment = small.length >= 3 ? small.filter((w) => big.has(w)).length / small.length : 0;
  return round(Math.max(uni, bi, containment * 0.9));
}
function bigrams(tokens) {
  const s = /* @__PURE__ */ new Set();
  for (let i = 0; i < tokens.length - 1; i++) s.add(`${tokens[i]} ${tokens[i + 1]}`);
  return s;
}
function jaccard(a, b) {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter++;
  return inter / (a.size + b.size - inter);
}
function fingerprintsFor(draft) {
  const fps = [
    { type: "topic", value: normalizeText(draft.topic) },
    { type: "phrase", value: normalizeText(draft.key_phrase) },
    { type: "cta", value: normalizeText(draft.cta) },
    { type: "structure", value: draft.structure }
  ];
  if (draft.metaphor.trim()) fps.push({ type: "metaphor", value: normalizeText(draft.metaphor) });
  for (const h of draft.hook_options) fps.push({ type: "hook", value: normalizeText(h) });
  return fps.filter((f) => f.value.length > 0);
}
function checkRepetition(candidate, recent, config = DEFAULT_REPETITION_CONFIG) {
  const hits = [];
  for (const c of candidate) {
    if (c.type === "structure") {
      const window = uniqueByItem(recent.filter((r) => r.type === "structure")).slice(0, config.structureWindow);
      const count = window.filter((r) => r.value === c.value).length;
      if (count + 1 > config.structureMaxInWindow) hits.push({ type: "structure", candidate: c.value, previous: c.value, similarity: round((count + 1) / (window.length + 1)) });
      continue;
    }
    if (c.type === "cta") {
      const same = recent.filter((r) => r.type === "cta" && similarity(r.value, c.value) >= 0.8);
      if (same.length >= config.ctaMaxRepeats) hits.push({ type: "cta", candidate: c.value, previous: same[0].value, similarity: 1 });
      continue;
    }
    const threshold = config.thresholds[c.type];
    const comparable = c.type === "hook" || c.type === "phrase" ? ["hook", "phrase"] : [c.type];
    let best = null;
    for (const r of recent) {
      if (!comparable.includes(r.type)) continue;
      const sim = similarity(c.value, r.value);
      if (sim >= threshold && (!best || sim > best.similarity)) best = { type: c.type, candidate: c.value, previous: r.value, similarity: sim };
    }
    if (best) hits.push(best);
  }
  return { repeated: hits.length > 0, hits };
}
function uniqueByItem(fps) {
  const seen = /* @__PURE__ */ new Set();
  return fps.filter((f, i) => {
    const key = f.contentItemId ?? `#${i}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
var TYPE_LABEL = {
  topic: "assunto",
  phrase: "frase",
  metaphor: "met\xE1fora",
  hook: "gancho",
  cta: "CTA",
  structure: "estrutura"
};
function describeAvoidance(report) {
  const types = [...new Set(report.hits.map((h) => h.type))];
  return types.map((t) => `Evitei repetir ${TYPE_LABEL[t]} usado recentemente.`);
}
function avoidanceInstructions(report) {
  if (!report.repeated) return "";
  const lines = report.hits.map((h) => `- ${TYPE_LABEL[h.type]} parecido com algo recente: "${h.previous}"`);
  return `O rascunho anterior repetiu conte\xFAdo recente. Crie OUTRO \xE2ngulo, sem reaproveitar:
${lines.join("\n")}`;
}
function round(n) {
  return Math.round(n * 100) / 100;
}

// ../../packages/domain/src/sync.ts
var SYNC_POLICY = { baseDelayMs: 5e3, maxDelayMs: 30 * 6e4, maxAttempts: 8 };

// ../../packages/domain/src/ai/contract.ts
import { z } from "npm:zod@4";
var PROMPT_VERSION = "content-v1.1.0";
var NARRATIVE_STRUCTURES = ["confissao", "pergunta", "contraste", "historia", "conselho", "observacao"];
var PLATFORMS = ["instagram", "tiktok", "facebook", "youtube_shorts"];
var text = (min = 1, max = 2e3) => z.string().trim().min(min).max(max);
var ContentDraftSchema = z.object({
  title: text(3, 120),
  pillar: text(2, 60),
  format: z.enum(["thought", "main_video", "story", "broll"]),
  duration_seconds: z.number().int().min(3).max(180),
  structure: z.enum(NARRATIVE_STRUCTURES),
  topic: text(3, 200),
  key_phrase: text(3, 300),
  metaphor: z.string().trim().max(200),
  hook_options: z.array(text(3, 200)).length(3),
  narrative: z.object({ e: text(3, 800), mas: text(3, 800), por_isso: text(3, 800) }),
  script: text(10, 4e3),
  screen_text: z.string().trim().max(120),
  cta: text(2, 200),
  caption: z.object({
    instagram: text(3, 2200),
    tiktok: text(3, 2200),
    facebook: text(3, 5e3),
    youtube_shorts: text(3, 5e3)
  }),
  hashtags: z.array(z.string().trim().regex(/^#[\p{L}\p{N}_]+$/u)).min(1).max(15),
  recording_suggestions: z.array(z.object({ scene: text(2, 200), duration_seconds: z.number().int().min(1).max(60), location_hint: z.string().trim().max(200) })).min(1).max(8),
  versions: z.array(z.object({ duration_seconds: z.number().int().min(5).max(180), script: text(5, 4e3) })).max(4)
});
var GenerateRequestSchema = z.object({
  workspace_id: z.uuid(),
  content_item_id: z.uuid().nullable(),
  format: z.enum(["thought", "main_video"]),
  pillar_slug: text(2, 60),
  event_text: z.string().trim().max(1500).nullable()
});
function parseDraft(input) {
  const r = ContentDraftSchema.safeParse(input);
  if (r.success) return { ok: true, draft: r.data };
  return { ok: false, errors: r.error.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`) };
}
var STRIP_KEYS = /* @__PURE__ */ new Set(["$schema", "minItems", "maxItems", "minLength", "maxLength", "minimum", "maximum", "pattern", "format"]);
function contentDraftJsonSchema() {
  const raw = z.toJSONSchema(ContentDraftSchema, { target: "draft-7" });
  return strip(raw);
}
function strip(node) {
  if (Array.isArray(node)) return node.map(strip);
  if (node && typeof node === "object") {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      if (STRIP_KEYS.has(k)) continue;
      out[k] = strip(v);
    }
    if (out.type === "object") out.additionalProperties = false;
    return out;
  }
  return node;
}

// ../../packages/domain/src/ai/prompt.ts
var RODRIGO_PROFILE = {
  displayName: "Rodrigo Serra",
  handle: "RodrigoSerra.me",
  positioning: "Vida real, evolu\xE7\xE3o pessoal e reflex\xF5es de um homem 40+.",
  signature: "RodrigoSerra.me",
  closingPhrase: "E se der certo!",
  voiceRules: [
    "humano, pr\xF3ximo, simples, direto e esperan\xE7oso",
    "fala com UMA pessoa, nunca com uma plateia",
    "nunca soa como guru ou coach gen\xE9rico",
    "evita jarg\xE3o motivacional (ex.: 'saia da zona de conforto', 'mindset', 'voc\xEA \xE9 incr\xEDvel')",
    "exemplos concretos do dia a dia, n\xE3o abstra\xE7\xF5es"
  ]
};
var DURATION_RANGE = {
  thought: [5, 15],
  main_video: [45, 120]
};
function buildPrompt(input) {
  const [min, max] = DURATION_RANGE[input.format];
  const system = [
    `Voc\xEA \xE9 o roteirista pessoal de ${input.profile.displayName} (${input.profile.handle}). Posicionamento: ${input.profile.positioning}`,
    `Voz: ${input.profile.voiceRules.join("; ")}.`,
    "Escreva em portugu\xEAs do Brasil, como fala, frases curtas, sem emojis no roteiro.",
    "Estrutura narrativa obrigat\xF3ria: E (situa\xE7\xE3o real) -> MAS (tens\xE3o/virada) -> POR ISSO (aprendizado/a\xE7\xE3o).",
    `O roteiro TERMINA exatamente com a frase de fechamento: "${input.profile.closingPhrase}" \u2014 n\xE3o altere essa frase.`,
    `As legendas terminam com a assinatura ${input.profile.signature}.`,
    "Nunca prometa viraliza\xE7\xE3o, resultado garantido ou n\xFAmeros de alcance.",
    "D\xEA 3 ganchos diferentes entre si (formas diferentes: pergunta, confiss\xE3o, contraste...).",
    "Regras de reten\xE7\xE3o para v\xEDdeo curto (Reels/TikTok/Shorts):",
    "- o gancho prende nos 2 primeiros segundos: at\xE9 12 palavras, concreto, abre uma lacuna de curiosidade ou quebra uma expectativa;",
    "- uma \xFAnica ideia por v\xEDdeo, com um detalhe espec\xEDfico e real (lugar, hora, objeto, frase ouvida) em vez de abstra\xE7\xE3o;",
    "- tens\xE3o no MAS: algo que o espectador tamb\xE9m vive e n\xE3o admite;",
    "- o POR ISSO entrega uma virada pr\xE1tica que d\xE1 vontade de salvar ou mandar para algu\xE9m;",
    "- o CTA pede uma resposta simples nos coment\xE1rios ligada ao tema (nada de 'curte e compartilha');",
    "- screen_text: 2 a 5 palavras que resumem o v\xEDdeo sem repetir o gancho;",
    "- legendas por plataforma adaptadas (TikTok curta e direta; Instagram com respiro; YouTube Shorts com t\xEDtulo forte);",
    "Responda somente no JSON do schema."
  ].join("\n");
  const user = [
    `Formato: ${input.format === "thought" ? "Pensamento do Dia" : "V\xEDdeo principal"} (${min}\u2013${max}s).`,
    `Pilar editorial: ${input.pillarName}.`,
    input.eventText ? `Acontecimento real de hoje contado pelo criador (transforme em conte\xFAdo, preserve os fatos): "${input.eventText}"` : "Sem acontecimento espec\xEDfico: parta de uma situa\xE7\xE3o comum e concreta do dia dele.",
    input.format === "main_video" ? "Inclua em 'versions' varia\xE7\xF5es de 15s, 30s e 60s quando fizer sentido." : "Em 'versions' inclua no m\xE1ximo uma varia\xE7\xE3o de at\xE9 15s.",
    input.recentSummaries.length ? `Conte\xFAdos recentes (n\xE3o repita assunto, frase, met\xE1fora, gancho, CTA nem estrutura):
${input.recentSummaries.map((s) => `- ${s}`).join("\n")}` : "",
    input.avoid
  ].filter(Boolean).join("\n\n");
  return { system, user, promptVersion: PROMPT_VERSION };
}
var PLATFORM_LIMITS = { instagram: 2200, tiktok: 2200, facebook: 5e3, youtube_shorts: 5e3 };
function finalizeDraft(draft, profile) {
  const closing = profile.closingPhrase.trim();
  const withClosing = (script) => {
    let body = script.trim();
    const idx = body.toLowerCase().lastIndexOf(closing.toLowerCase().replace(/[!.]+$/, ""));
    if (idx >= 0 && body.length - idx <= closing.length + 2) body = body.slice(0, idx).trim();
    return closing ? `${body}

${closing}` : body;
  };
  const tags = draft.hashtags.join(" ");
  const caption = {};
  for (const p of PLATFORMS) {
    let c = draft.caption[p].trim();
    if (!c.includes(profile.signature)) c = `${c}

${profile.signature}`;
    if ((p === "instagram" || p === "tiktok") && !c.includes(draft.hashtags[0] ?? "#")) c = `${c}

${tags}`;
    caption[p] = c.slice(0, PLATFORM_LIMITS[p]);
  }
  return {
    ...draft,
    script: withClosing(draft.script),
    versions: draft.versions.map((v) => ({ ...v, script: withClosing(v.script) })),
    caption
  };
}
function summarizeForMemory(d) {
  return [d.topic, `frase: "${d.key_phrase}"`, d.metaphor ? `met\xE1fora: ${d.metaphor}` : "", `CTA: ${d.cta}`, `estrutura: ${d.structure}`].filter(Boolean).join(" | ");
}

// src/edge.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2";

// src/adapters.ts
import { createClient } from "npm:@supabase/supabase-js@2";
function geminiClient(apiKey, model, fetchImpl = fetch) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;
  async function call(body) {
    const res = await fetchImpl(url, { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey }, body: JSON.stringify(body) });
    return { res, json: await res.json().catch(() => ({})) };
  }
  return {
    model,
    source: "gemini",
    async complete({ system, user, schema }) {
      const base = { systemInstruction: { parts: [{ text: system }] }, contents: [{ role: "user", parts: [{ text: user }] }] };
      let r = await call({ ...base, generationConfig: { temperature: 0.9, responseMimeType: "application/json", responseJsonSchema: schema } });
      if (r.res.status === 400) r = await call({ ...base, generationConfig: { temperature: 0.9, responseMimeType: "application/json" } });
      if (!r.res.ok) throw new Error(`gemini HTTP ${r.res.status}: ${r.json.error?.message ?? ""}`.slice(0, 200));
      const text2 = r.json.candidates?.[0]?.content?.parts?.map((p) => p.text ?? "").join("") ?? "";
      if (!text2) throw new Error("empty gemini response");
      return JSON.parse(text2.replace(/^```(?:json)?\s*|\s*```$/g, ""));
    }
  };
}
function userSupabase(url, anonKey, accessToken) {
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${accessToken}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var MEMORY_WINDOW = 120;
function supabaseMemory(db, userId) {
  return {
    async canWrite(ws) {
      const { data, error } = await db.rpc("can_write_workspace", { ws });
      if (error) throw error;
      return data === true;
    },
    async profile(ws) {
      const { data, error } = await db.from("creator_profiles").select("*").eq("workspace_id", ws).maybeSingle();
      if (error) throw error;
      if (!data) throw Object.assign(new Error("workspace not found"), { status: 404 });
      return {
        displayName: data.display_name,
        handle: data.handle ?? data.display_name,
        positioning: data.positioning ?? "",
        signature: data.signature ?? data.handle ?? "",
        closingPhrase: data.closing_phrase ?? "",
        voiceRules: data.voice_rules?.length ? data.voice_rules : RODRIGO_PROFILE.voiceRules
      };
    },
    async pillarName(ws, slug) {
      const { data } = await db.from("content_pillars").select("name").eq("workspace_id", ws).eq("slug", slug).maybeSingle();
      return data?.name ?? slug;
    },
    async recentFingerprints(ws) {
      const { data, error } = await db.from("content_fingerprints").select("fingerprint_type, fingerprint, content_item_id, created_at").eq("workspace_id", ws).order("created_at", { ascending: false }).limit(MEMORY_WINDOW);
      if (error) throw error;
      return (data ?? []).map((r) => ({ type: r.fingerprint_type, value: r.fingerprint, contentItemId: r.content_item_id, createdAt: r.created_at }));
    },
    async recentSummaries(ws) {
      const { data } = await db.from("scripts").select("draft").eq("workspace_id", ws).order("created_at", { ascending: false }).limit(10);
      return (data ?? []).filter((r) => r.draft?.topic).map((r) => summarizeForMemory(r.draft));
    },
    async saveRun(run) {
      const { error } = await db.from("generation_runs").insert({
        workspace_id: run.workspaceId,
        content_item_id: null,
        source: run.model.startsWith("gemini") ? "gemini" : "openai",
        model: run.model,
        prompt_version: run.promptVersion,
        request: run.request,
        response: run.response,
        accepted: run.accepted,
        rejection_reason: run.rejectionReason,
        repetition: run.repetition ?? {},
        latency_ms: run.latencyMs,
        created_by: userId
      });
      if (error) console.warn(JSON.stringify({ level: "warn", msg: "generation_run not saved", code: error.code }));
    }
  };
}

// src/generation.service.ts
var LlmUnavailableError = class extends Error {
};
var MAX_ATTEMPTS = 3;
async function generateContent(req, llm, memory) {
  if (!await memory.canWrite(req.workspace_id)) throw Object.assign(new Error("forbidden"), { status: 403 });
  const [profile, pillarName, recent, summaries] = await Promise.all([
    memory.profile(req.workspace_id),
    memory.pillarName(req.workspace_id, req.pillar_slug),
    memory.recentFingerprints(req.workspace_id),
    memory.recentSummaries(req.workspace_id)
  ]);
  const schema = contentDraftJsonSchema();
  let avoid = "";
  const avoided = [];
  let fallback = null;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const prompt = buildPrompt({ profile, pillarName, format: req.format, eventText: req.event_text, recentSummaries: summaries, avoid });
    const started = Date.now();
    let raw;
    try {
      raw = await llm.complete({ system: prompt.system, user: prompt.user, schema });
    } catch (e) {
      throw new LlmUnavailableError(e instanceof Error ? e.message : "llm error");
    }
    const base = { workspaceId: req.workspace_id, contentItemId: req.content_item_id, model: llm.model, promptVersion: prompt.promptVersion, request: { ...req, attempt }, response: raw, latencyMs: Date.now() - started };
    const parsed = parseDraft(raw);
    if (!parsed.ok) {
      await memory.saveRun({ ...base, accepted: false, rejectionReason: `schema: ${parsed.errors.slice(0, 5).join("; ")}`, repetition: null });
      continue;
    }
    const draft = finalizeDraft(parsed.draft, profile);
    const report = checkRepetition(fingerprintsFor(draft), recent);
    if (report.repeated) {
      await memory.saveRun({ ...base, accepted: false, rejectionReason: "repetition", repetition: report });
      avoided.push(...describeAvoidance(report));
      avoid = avoidanceInstructions(report);
      if (!fallback || report.hits.length < fallback.report.hits.length) fallback = { draft, report };
      continue;
    }
    await memory.saveRun({ ...base, accepted: true, rejectionReason: null, repetition: report });
    return respond(draft, llm, attempt, avoided, []);
  }
  if (fallback) {
    return respond(fallback.draft, llm, MAX_ATTEMPTS, avoided, ["N\xE3o consegui um \xE2ngulo 100% in\xE9dito; revise o texto antes de gravar."]);
  }
  throw new LlmUnavailableError("A IA n\xE3o retornou um roteiro v\xE1lido.");
}
function respond(draft, llm, attempts, avoided, extra) {
  const model = llm.model;
  const unique = [...new Set(avoided)];
  return {
    draft,
    fingerprints: fingerprintsFor(draft),
    meta: { source: llm.source ?? "openai", model, prompt_version: PROMPT_VERSION, attempts, avoided: unique },
    notices: [...unique, ...extra]
  };
}

// src/edge.ts
var json = (status, body) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
Deno.serve(async (req) => {
  if (req.method !== "POST") return json(405, { code: "method_not_allowed" });
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? req.headers.get("apikey") ?? "";
  const key = Deno.env.get("GEMINI_API_KEY");
  const token = /^Bearer (.+)$/.exec(req.headers.get("Authorization") ?? "")?.[1];
  if (!token) return json(401, { code: "unauthorized" });
  const { data, error } = await createClient2(url, anon, { auth: { persistSession: false } }).auth.getUser(token);
  if (error || !data.user) return json(401, { code: "unauthorized" });
  const parsed = GenerateRequestSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) return json(400, { code: "invalid_request" });
  if (!key) return json(503, { code: "llm_not_configured" });
  try {
    const llm = geminiClient(key, Deno.env.get("GEMINI_MODEL") ?? "gemini-flash-latest");
    return json(200, await generateContent(parsed.data, llm, supabaseMemory(userSupabase(url, anon, token), data.user.id)));
  } catch (e) {
    const status = e.status;
    if (status === 403 || status === 404) return json(404, { code: "workspace_not_found" });
    if (e instanceof LlmUnavailableError) return json(502, { code: "llm_unavailable" });
    console.error(JSON.stringify({ msg: "generate.failed", error: e instanceof Error ? e.message : String(e) }));
    return json(500, { code: "internal_error" });
  }
});
