// GENERATED by apps/api build:mcp — do not edit

// src/mcp-edge.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2";

// ../../packages/domain/src/pillars.ts
var RODRIGO_PILLARS = [
  { slug: "reflexao", name: "Motiva\xE7\xE3o e reflex\xE3o real", targetPercent: 40 },
  { slug: "vida-real", name: "Vida real / homem 40+ / maturidade", targetPercent: 20 },
  { slug: "academia", name: "Academia e evolu\xE7\xE3o", targetPercent: 15 },
  { slug: "familia", name: "Fam\xEDlia", targetPercent: 10 },
  { slug: "humor", name: "Humor", targetPercent: 10 },
  { slug: "empreendedorismo", name: "Empreendedorismo", targetPercent: 5 }
];
var EPSILON = 0.01;
function pickNextPillar(pillars, recentPillarSlugs, exclude = []) {
  const active = pillars.filter((p) => p.active !== false && p.targetPercent > 0);
  const candidates = active.filter((p) => !exclude.includes(p.slug));
  const pool = candidates.length > 0 ? candidates : active;
  if (pool.length === 0) throw new Error("Nenhum pilar ativo configurado.");
  const known = recentPillarSlugs.filter((s) => active.some((p) => p.slug === s));
  const nextTotal = known.length + 1;
  let best = pool[0];
  let bestScore = -Infinity;
  for (const p of pool) {
    const count = known.filter((s) => s === p.slug).length;
    const score = p.targetPercent / 100 * nextTotal - count;
    if (score > bestScore + EPSILON || Math.abs(score - bestScore) <= EPSILON && p.targetPercent > best.targetPercent) {
      best = p;
      bestScore = score;
    }
  }
  return best;
}

// ../../packages/domain/src/planner.ts
var RODRIGO_WEEKDAY_BLOCKS = [
  { startTime: "08:45", title: "Caf\xE9 / B-roll", contentHint: "3 segundos do caf\xE9", optional: false, format: "broll" },
  { startTime: "09:10", title: "In\xEDcio do trabalho / B-roll", contentHint: "entrada no expediente", optional: false, format: "broll" },
  { startTime: "10:30", title: "Pensamento do Dia", contentHint: "v\xEDdeo curto 5\u201315s", optional: false, format: "thought" },
  { startTime: "12:15", title: "Almo\xE7o opcional", contentHint: "take de 3 segundos", optional: true, format: "broll" },
  { startTime: "15:00", title: "Trabalho / B-roll", contentHint: "algo real acontecendo na empresa", optional: true, format: "broll" },
  { startTime: "17:30", title: "Fim do expediente", contentHint: "encerramento do trabalho", optional: false, format: "broll" },
  { startTime: "19:15", title: "Prepara\xE7\xE3o para academia", contentHint: "pr\xE9-treino / prepara\xE7\xE3o", optional: false, format: "broll" },
  { startTime: "19:30", title: "V\xEDdeo principal caminhando", contentHint: "45s\u20132m", optional: false, format: "main_video" },
  { startTime: "20:15", title: "Academia / B-roll", contentHint: "entrada, exerc\xEDcio ou final", optional: false, format: "broll" },
  { startTime: "21:30", title: "Fim do dia", contentHint: "encerramento", optional: false, format: "broll" }
];
function rodrigoRoutine(newId) {
  const blocks = [];
  for (let weekday = 1; weekday <= 5; weekday++) {
    for (const b of RODRIGO_WEEKDAY_BLOCKS) blocks.push({ ...b, id: newId(), weekday });
  }
  return blocks;
}
var DEFAULT_DURATION = { thought: 12, main_video: 60, story: 15, broll: 3 };
var FORMAT_LABEL = {
  thought: "Pensamento do Dia",
  main_video: "V\xEDdeo principal",
  story: "Story",
  broll: "B-roll"
};
function toLocalDateKey(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function localDateTime(dateKey, hhmm) {
  const [y, m, d] = dateKey.split("-").map(Number);
  const [h, mi] = hhmm.split(":").map(Number);
  return new Date(y, m - 1, d, h, mi, 0, 0);
}
function zonedDateTime(dateKey, hhmm, utcOffsetMinutes) {
  const [y, m, d] = dateKey.split("-").map(Number);
  const [h, mi] = hhmm.split(":").map(Number);
  return new Date(Date.UTC(y, m - 1, d, h, mi, 0, 0) - utcOffsetMinutes * 6e4);
}
var BRASILIA_OFFSET_MIN = -180;
function buildDayPlan(input) {
  const dateKey = input.dateKey ?? toLocalDateKey(input.date);
  const weekday = input.weekdayOverride ?? (input.dateKey ? (/* @__PURE__ */ new Date(`${input.dateKey}T12:00:00Z`)).getUTCDay() : input.date.getDay());
  const blocks = input.routine.filter((b) => b.weekday === weekday).sort((a, b) => a.startTime.localeCompare(b.startTime));
  const history = [...input.recentPillarSlugs];
  const contentItems = [];
  const tasks = blocks.map((b) => {
    const scheduledFor = (input.utcOffsetMinutes === void 0 ? localDateTime(dateKey, b.startTime) : zonedDateTime(dateKey, b.startTime, input.utcOffsetMinutes)).toISOString();
    let contentItemId = null;
    if (b.format === "thought" || b.format === "main_video") {
      const pillar = pickNextPillar(input.pillars, history, contentItems.map((c) => c.pillarSlug));
      history.push(pillar.slug);
      contentItemId = input.newId();
      contentItems.push({ id: contentItemId, workspaceId: input.workspaceId, date: dateKey, format: b.format, pillarSlug: pillar.slug, title: FORMAT_LABEL[b.format], status: "planned", scheduledFor });
    }
    return {
      id: input.newId(),
      workspaceId: input.workspaceId,
      contentItemId,
      scheduledFor,
      title: b.title,
      kind: b.format,
      hint: b.contentHint,
      suggestedDurationSeconds: DEFAULT_DURATION[b.format],
      optional: b.optional,
      status: "pending",
      notes: null,
      takeId: null,
      supersededBy: null,
      updatedAt: input.now
    };
  });
  return { date: dateKey, tasks, contentItems };
}
function pad(n) {
  return String(n).padStart(2, "0");
}

// ../../packages/domain/src/repetition.ts
var DEFAULT_REPETITION_CONFIG = {
  thresholds: { topic: 0.5, phrase: 0.45, metaphor: 0.5, hook: 0.5 },
  ctaMaxRepeats: 2,
  structureMaxInWindow: 3,
  structureWindow: 5
};
var STOPWORDS = new Set(
  "a o as os um uma uns umas de da do das dos em na no nas nos por para pra pro com sem e ou que se me te nos voce voces eu ele ela eles elas isso isto esse essa este esta aquilo mais menos muito muita ja nao sim so ao aos \xE0 \xE0s \xE9 era ser foi vai vou ter tem tinha sua seu suas seus minha meu minhas meus tua teu como quando onde porque pq mas entao ent\xE3o hoje".split(
    " "
  ).map((w) => stripAccents(w))
);
function stripAccents(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "");
}
function normalizeText(s) {
  return stripAccents(s.toLowerCase()).replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();
}
function stem(w) {
  return w.length > 4 ? w.replace(/(mente|coes|cao|oes|ais|eis|res|es|as|os|s)$/u, "") : w;
}
function contentTokens(s) {
  return normalizeText(s).split(" ").filter((w) => w.length > 1 && !STOPWORDS.has(w)).map(stem);
}
function similarity(a, b) {
  const ta = contentTokens(a);
  const tb = contentTokens(b);
  if (ta.length === 0 || tb.length === 0) return 0;
  const uni = jaccard(new Set(ta), new Set(tb));
  const bi = jaccard(bigrams(ta), bigrams(tb));
  const small = ta.length <= tb.length ? ta : tb;
  const big = new Set(ta.length <= tb.length ? tb : ta);
  const containment = small.length >= 3 ? small.filter((w) => big.has(w)).length / small.length : 0;
  return round(Math.max(uni, bi, containment * 0.9));
}
function bigrams(tokens) {
  const s = /* @__PURE__ */ new Set();
  for (let i = 0; i < tokens.length - 1; i++) s.add(`${tokens[i]} ${tokens[i + 1]}`);
  return s;
}
function jaccard(a, b) {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter++;
  return inter / (a.size + b.size - inter);
}
function fingerprintsFor(draft) {
  const fps = [
    { type: "topic", value: normalizeText(draft.topic) },
    { type: "phrase", value: normalizeText(draft.key_phrase) },
    { type: "cta", value: normalizeText(draft.cta) },
    { type: "structure", value: draft.structure }
  ];
  if (draft.metaphor.trim()) fps.push({ type: "metaphor", value: normalizeText(draft.metaphor) });
  for (const h of draft.hook_options) fps.push({ type: "hook", value: normalizeText(h) });
  return fps.filter((f) => f.value.length > 0);
}
function checkRepetition(candidate, recent, config = DEFAULT_REPETITION_CONFIG) {
  const hits = [];
  for (const c of candidate) {
    if (c.type === "structure") {
      const window = uniqueByItem(recent.filter((r) => r.type === "structure")).slice(0, config.structureWindow);
      const count = window.filter((r) => r.value === c.value).length;
      if (count + 1 > config.structureMaxInWindow) hits.push({ type: "structure", candidate: c.value, previous: c.value, similarity: round((count + 1) / (window.length + 1)) });
      continue;
    }
    if (c.type === "cta") {
      const same = recent.filter((r) => r.type === "cta" && similarity(r.value, c.value) >= 0.8);
      if (same.length >= config.ctaMaxRepeats) hits.push({ type: "cta", candidate: c.value, previous: same[0].value, similarity: 1 });
      continue;
    }
    const threshold = config.thresholds[c.type];
    const comparable = c.type === "hook" || c.type === "phrase" ? ["hook", "phrase"] : [c.type];
    let best = null;
    for (const r of recent) {
      if (!comparable.includes(r.type)) continue;
      const sim = similarity(c.value, r.value);
      if (sim >= threshold && (!best || sim > best.similarity)) best = { type: c.type, candidate: c.value, previous: r.value, similarity: sim };
    }
    if (best) hits.push(best);
  }
  return { repeated: hits.length > 0, hits };
}
function uniqueByItem(fps) {
  const seen = /* @__PURE__ */ new Set();
  return fps.filter((f, i) => {
    const key = f.contentItemId ?? `#${i}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
var TYPE_LABEL = {
  topic: "assunto",
  phrase: "frase",
  metaphor: "met\xE1fora",
  hook: "gancho",
  cta: "CTA",
  structure: "estrutura"
};
function describeAvoidance(report) {
  const types = [...new Set(report.hits.map((h) => h.type))];
  return types.map((t) => `Evitei repetir ${TYPE_LABEL[t]} usado recentemente.`);
}
function round(n) {
  return Math.round(n * 100) / 100;
}

// ../../packages/domain/src/sync.ts
var SYNC_POLICY = { baseDelayMs: 5e3, maxDelayMs: 30 * 6e4, maxAttempts: 8 };

// ../../packages/domain/src/ai/contract.ts
import { z } from "npm:zod@4";
var PROMPT_VERSION = "content-v1.3.0";
var NARRATIVE_STRUCTURES = ["confissao", "pergunta", "contraste", "historia", "conselho", "observacao"];
var PLATFORMS = ["instagram", "tiktok", "facebook", "youtube_shorts"];
var text = (min = 1, max = 2e3) => z.string().trim().min(min).max(max);
var ContentDraftSchema = z.object({
  title: text(3, 120),
  pillar: text(2, 60),
  format: z.enum(["thought", "main_video", "story", "broll"]),
  duration_seconds: z.number().int().min(3).max(180),
  structure: z.enum(NARRATIVE_STRUCTURES),
  topic: text(3, 200),
  key_phrase: text(3, 300),
  metaphor: z.string().trim().max(200),
  hook_options: z.array(text(3, 200)).length(3),
  narrative: z.object({ e: text(3, 800), mas: text(3, 800), por_isso: text(3, 800) }),
  script: text(10, 4e3),
  screen_text: z.string().trim().max(120),
  cta: text(2, 200),
  caption: z.object({
    instagram: text(3, 2200),
    tiktok: text(3, 2200),
    facebook: text(3, 5e3),
    youtube_shorts: text(3, 5e3)
  }),
  hashtags: z.array(z.string().trim().regex(/^#[\p{L}\p{N}_]+$/u)).min(1).max(15),
  recording_suggestions: z.array(z.object({ scene: text(2, 200), duration_seconds: z.number().int().min(1).max(60), location_hint: z.string().trim().max(200) })).min(1).max(8),
  versions: z.array(z.object({ duration_seconds: z.number().int().min(5).max(180), script: text(5, 4e3) })).max(4)
});
var GenerateRequestSchema = z.object({
  workspace_id: z.uuid(),
  content_item_id: z.uuid().nullable(),
  format: z.enum(["thought", "main_video"]),
  pillar_slug: text(2, 60),
  event_text: z.string().trim().max(1500).nullable(),
  /** project briefing from the studio (mode, filmed SKU, ice-cream source, recipe) — optional */
  brief: z.string().trim().max(1500).nullable().optional()
});
function parseDraft(input) {
  const r = ContentDraftSchema.safeParse(input);
  if (r.success) return { ok: true, draft: r.data };
  return { ok: false, errors: r.error.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`) };
}

// ../../packages/domain/src/ai/prompt.ts
var RODRIGO_PROFILE = {
  displayName: "Rodrigo Serra",
  handle: "RodrigoSerra.me",
  positioning: "Vida real, evolu\xE7\xE3o pessoal e reflex\xF5es de um homem 40+.",
  signature: "RodrigoSerra.me",
  closingPhrase: "E se der certo!",
  voiceRules: [
    "humano, pr\xF3ximo, simples, direto e esperan\xE7oso",
    "fala com UMA pessoa, nunca com uma plateia",
    "nunca soa como guru ou coach gen\xE9rico",
    "evita jarg\xE3o motivacional (ex.: 'saia da zona de conforto', 'mindset', 'voc\xEA \xE9 incr\xEDvel')",
    "exemplos concretos do dia a dia, n\xE3o abstra\xE7\xF5es"
  ]
};
var VIRAL_FORMATS = [
  "\u201Cningu\xE9m te conta que\u2026\u201D (revela algo que todo mundo vive e ningu\xE9m fala)",
  "\u201Ceu costumava\u2026 hoje eu\u2026\u201D (antes e depois pessoal)",
  "\u201Co erro que eu cometi com\u2026\u201D (confiss\xE3o com aprendizado)",
  "pergunta direta que o espectador responde na cabe\xE7a (\u201Cquando foi a \xFAltima vez que voc\xEA\u2026?\u201D)",
  "contraste: o que todo mundo pensa \xD7 o que acontece de verdade",
  "cena concreta do dia (lugar, hora, frase ouvida) que vira li\xE7\xE3o",
  "lista curta de 3 (\u201C3 coisas que\u2026\u201D), s\xF3 no v\xEDdeo principal"
];
var DURATION_RANGE = {
  thought: [5, 15],
  main_video: [45, 120]
};
var BUSINESS_MAIN_RANGE = [30, 90];
function buildPrompt(input) {
  const b = input.profile.kind === "empresa" ? input.profile.business : void 0;
  const [min, max] = b && input.format === "main_video" ? BUSINESS_MAIN_RANGE : DURATION_RANGE[input.format];
  const system = b ? businessSystem(input.profile, b) : [
    `Voc\xEA \xE9 o roteirista pessoal de ${input.profile.displayName} (${input.profile.handle}). Posicionamento: ${input.profile.positioning}`,
    `Voz: ${input.profile.voiceRules.join("; ")}.`,
    "Escreva em portugu\xEAs do Brasil, como fala, frases curtas, sem emojis no roteiro.",
    "Estrutura narrativa obrigat\xF3ria: E (situa\xE7\xE3o real) -> MAS (tens\xE3o/virada) -> POR ISSO (aprendizado/a\xE7\xE3o).",
    `O roteiro TERMINA exatamente com a frase de fechamento: "${input.profile.closingPhrase}" \u2014 n\xE3o altere essa frase.`,
    `As legendas terminam com a assinatura ${input.profile.signature}.`,
    "Nunca prometa viraliza\xE7\xE3o, resultado garantido ou n\xFAmeros de alcance.",
    "D\xEA 3 ganchos diferentes entre si (formas diferentes: pergunta, confiss\xE3o, contraste...).",
    "Regras de reten\xE7\xE3o para v\xEDdeo curto (Reels/TikTok/Shorts):",
    "- o gancho prende nos 2 primeiros segundos: at\xE9 12 palavras, concreto, abre uma lacuna de curiosidade ou quebra uma expectativa;",
    "- uma \xFAnica ideia por v\xEDdeo, com um detalhe espec\xEDfico e real (lugar, hora, objeto, frase ouvida) em vez de abstra\xE7\xE3o;",
    "- tens\xE3o no MAS: algo que o espectador tamb\xE9m vive e n\xE3o admite;",
    "- o POR ISSO entrega uma virada pr\xE1tica que d\xE1 vontade de salvar ou mandar para algu\xE9m;",
    "- a 1\xAA frase j\xE1 diz o assunto com a palavra que algu\xE9m pesquisaria (a plataforma transcreve a fala e usa na busca); nada de 'oi, gente' nem contexto antes do gancho;",
    "- o que mais espalha \xE9 algu\xE9m MANDAR o v\xEDdeo para outra pessoa: escreva pensando em quem vai receber;",
    "- o CTA \xE9 UM destes, o que combinar: pedir para mandar para algu\xE9m espec\xEDfico ('manda para quem\u2026') ou uma pergunta simples para responder nos coment\xE1rios, ligada ao tema (nada de 'curte e compartilha');",
    "- screen_text: 2 a 5 palavras que resumem o v\xEDdeo sem repetir o gancho;",
    "- legendas por plataforma adaptadas (TikTok curta e direta; Instagram com respiro; YouTube Shorts com t\xEDtulo forte);",
    "Formato que viraliza (escolha UM que combine com o tema e use de verdade, sem for\xE7ar):",
    ...VIRAL_FORMATS.map((f) => `- ${f};`),
    "Coer\xEAncia (o texto \xE9 lido em voz alta, parte por parte, e precisa fazer sentido para quem nunca viu o perfil):",
    "- uma ideia s\xF3, do come\xE7o ao fim; cada frase continua a anterior (nada de frases soltas de efeito, colcha de retalhos ou prov\xE9rbio gen\xE9rico);",
    "- o gancho promete algo e o final entrega exatamente isso; o tema do dia (pilar) \xE9 o assunto, n\xE3o um detalhe;",
    "- nada de met\xE1fora confusa nem palavra dif\xEDcil; se uma frase n\xE3o d\xE1 para entender de primeira, reescreva;",
    "- antes de responder, leia o roteiro inteiro em voz alta mentalmente: se algum trecho n\xE3o se liga ao resto, corte.",
    "Responda somente no JSON do schema."
  ].join("\n");
  const user = [
    b ? `Pilar de venda: ${input.pillarName}. Antes de escrever, decida (coerentes entre si): p\xFAblico, n\xEDvel de consci\xEAncia, UMA dor, UMA obje\xE7\xE3o, UM desejo, UMA prova visual, UMA emo\xE7\xE3o e a a\xE7\xE3o esperada. Sem isso, n\xE3o escreva.` : "",
    `Formato: ${input.format === "thought" ? "Pensamento do Dia" : "V\xEDdeo principal"} (${min}\u2013${max}s).`,
    b ? "" : `Pilar editorial: ${input.pillarName}.`,
    input.eventText ? `${b ? "Situa\xE7\xE3o real da empresa hoje" : "Acontecimento real de hoje contado pelo criador"} (transforme em conte\xFAdo, preserve os fatos): "${input.eventText}"` : b ? "Sem acontecimento espec\xEDfico: parta de uma dor real do cliente." : "Sem acontecimento espec\xEDfico: parta de uma situa\xE7\xE3o comum e concreta do dia dele.",
    input.brief ? `Briefing do projeto (siga \xE0 risca; dados do equipamento s\xF3 os daqui): ${input.brief}` : "",
    input.format === "main_video" ? "Inclua em 'versions' varia\xE7\xF5es de 15s, 30s e 60s quando fizer sentido." : "Pensamento do Dia: 3 a 5 frases curtas no 'script'. A 1\xAA frase \xC9 o gancho (at\xE9 12 palavras; \xE9 gravada sozinha como 'Gancho'); as do meio desenvolvem UMA ideia; a \xFAltima antes do fechamento \xE9 a virada que d\xE1 vontade de mandar para algu\xE9m. Em 'versions' inclua no m\xE1ximo uma varia\xE7\xE3o de at\xE9 15s.",
    input.recentSummaries.length ? `Conte\xFAdos recentes (n\xE3o repita assunto, frase, met\xE1fora, gancho, CTA nem estrutura):
${input.recentSummaries.map((s) => `- ${s}`).join("\n")}` : "",
    input.avoid
  ].filter(Boolean).join("\n\n");
  return { system, user, promptVersion: PROMPT_VERSION };
}
function businessSystem(profile, b) {
  const list = (xs) => xs.map((x) => `- ${x}`).join("\n");
  return [
    `Voc\xEA \xE9 o roteirista de v\xEDdeos de venda da ${b.brand} (${b.product}). Posicionamento: ${profile.positioning}`,
    `Quem compra \xE9 empres\xE1rio: algu\xE9m que ${b.audience}. N\xE3o \xE9 consumidor final.`,
    `Voz: ${profile.voiceRules.join("; ")}.`,
    "Pergunta central de todo v\xEDdeo: o que impede esse empres\xE1rio de comprar hoje? O v\xEDdeo elimina UMA d\xFAvida e mostra UMA prova.",
    "Mapeie a estrutura assim: E = a dor real do cliente (concreta, do dia a dia da opera\xE7\xE3o); MAS = a obje\xE7\xE3o ou a cren\xE7a errada, respondida sem enrolar; POR ISSO = a prova visual + o diferencial que resolve.",
    "O tipo de v\xEDdeo segue o pilar: Educa\xE7\xE3o = erro comum e como escolher; Autoridade = experi\xEAncia e f\xE1brica; Demonstra\xE7\xE3o = produto em uso com prova; Bastidores = produ\xE7\xE3o/qualidade; Comparativo = 'parece igual, mas n\xE3o \xE9'; Hist\xF3rias = caso real de cliente; Oferta = condi\xE7\xE3o e escassez REAIS, sem inventar.",
    b.noPrice ? "PROIBIDO falar pre\xE7o, valor, parcela, desconto em n\xFAmero ou 'R$' \u2014 nem no roteiro, nem na tela, nem nas legendas. Pre\xE7o \xE9 no atendimento." : "",
    "Nunca invente especifica\xE7\xE3o t\xE9cnica, n\xFAmero ou depoimento que n\xE3o esteja abaixo.",
    `Dores reais:
${list(b.pains)}`,
    `Desejos:
${list(b.desires)}`,
    `Obje\xE7\xF5es e respostas (use UMA por v\xEDdeo):
${b.objections.map((o) => `- "${o.objection}" \u2192 ${o.answer}`).join("\n")}`,
    `Provas visuais que d\xE1 para filmar (use em recording_suggestions):
${list(b.proofs)}`,
    `Diferenciais comprovados (pode afirmar):
${list(b.differentiators)}`,
    b.pendingClaims?.length ? `Alega\xE7\xF5es AINDA SEM PROVA \u2014 N\xC3O afirme nem cite n\xFAmeros delas:
${list(b.pendingClaims)}` : "",
    `CTAs poss\xEDveis (adapte, sem press\xE3o):
${list(b.ctas)}`,
    `As legendas terminam com a assinatura ${profile.signature}.`,
    "Gancho de at\xE9 12 palavras que para o scroll (dor financeira, curiosidade, compara\xE7\xE3o, autoridade ou erro). screen_text de 2 a 5 palavras.",
    "Legendas por plataforma adaptadas; no Facebook/Marketplace pode detalhar o uso do produto (sem pre\xE7o).",
    "Responda somente no JSON do schema."
  ].filter(Boolean).join("\n");
}
var PLATFORM_LIMITS = { instagram: 2200, tiktok: 2200, facebook: 5e3, youtube_shorts: 5e3 };
function finalizeDraft(draft, profile) {
  const closing = profile.closingPhrase.trim();
  const withClosing = (script) => {
    let body = script.trim();
    const idx = body.toLowerCase().lastIndexOf(closing.toLowerCase().replace(/[!.]+$/, ""));
    if (idx >= 0 && body.length - idx <= closing.length + 2) body = body.slice(0, idx).trim();
    return closing ? `${body}

${closing}` : body;
  };
  const tags = draft.hashtags.join(" ");
  const caption = {};
  for (const p of PLATFORMS) {
    let c = draft.caption[p].trim();
    if (!c.includes(profile.signature)) c = `${c}

${profile.signature}`;
    if ((p === "instagram" || p === "tiktok") && !c.includes(draft.hashtags[0] ?? "#")) c = `${c}

${tags}`;
    caption[p] = c.slice(0, PLATFORM_LIMITS[p]);
  }
  return {
    ...draft,
    script: withClosing(draft.script),
    versions: draft.versions.map((v) => ({ ...v, script: withClosing(v.script) })),
    caption
  };
}
function summarizeForMemory(d) {
  return [d.topic, `frase: "${d.key_phrase}"`, d.metaphor ? `met\xE1fora: ${d.metaphor}` : "", `CTA: ${d.cta}`, `estrutura: ${d.structure}`].filter(Boolean).join(" | ");
}

// ../../packages/domain/src/profiles.ts
var BUSINESS_PILLARS = [
  { slug: "educacao", name: "Educa\xE7\xE3o (erros e como escolher)", targetPercent: 30 },
  { slug: "autoridade", name: "Autoridade (experi\xEAncia e f\xE1brica)", targetPercent: 20 },
  { slug: "demonstracao", name: "Demonstra\xE7\xE3o (produto em uso)", targetPercent: 15 },
  { slug: "bastidores", name: "Bastidores", targetPercent: 10 },
  { slug: "comparativo", name: "Comparativo (parece igual, n\xE3o \xE9)", targetPercent: 10 },
  { slug: "historias", name: "Hist\xF3rias de cliente", targetPercent: 10 },
  { slug: "oferta", name: "Oferta (sem falar pre\xE7o)", targetPercent: 5 }
];
var CONTROLPOT_STRATEGY = {
  brand: "ControlPot",
  product: "mixer profissional de milk-shake",
  audience: "tem a\xE7aiteria, sorveteria, cafeteria ou franquia",
  pains: [
    "o milk-shake sai aguado em alguns dias",
    "cada funcion\xE1rio faz o milk-shake de um jeito",
    "a m\xE1quina perde pot\xEAncia bem no hor\xE1rio de pico",
    "a m\xE1quina quebra e a opera\xE7\xE3o para",
    "a assist\xEAncia demora e n\xE3o acha pe\xE7a",
    "o cliente prova uma vez e n\xE3o volta"
  ],
  desires: [
    "milk-shake cremoso igual todo dia",
    "atender r\xE1pido no pico sem dor de cabe\xE7a",
    "equipamento profissional que passa confian\xE7a",
    "suporte quando precisar"
  ],
  objections: [
    { objection: "Est\xE1 caro", answer: "Barato que para no pico sai caro: cada hora parada \xE9 venda perdida e cliente que n\xE3o volta." },
    { objection: "Outra marca \xE9 mais barata", answer: "Compara o resultado no copo e quanto tempo ela aguenta trabalhando todo dia, n\xE3o s\xF3 a etiqueta." },
    { objection: "E se quebrar?", answer: "Tem assist\xEAncia t\xE9cnica pr\xF3pria e pe\xE7a de reposi\xE7\xE3o, ent\xE3o a opera\xE7\xE3o n\xE3o fica parada esperando." },
    { objection: "Posso bater direto no copo?", answer: "Pode: d\xE1 para bater direto no copo pl\xE1stico, sem sujar outra caneca." },
    { objection: "Qual a diferen\xE7a pra uma comum?", answer: "N\xE3o precisa acreditar em mim: olha a textura no copo, lado a lado." }
  ],
  proofs: [
    "close na textura cremosa escorrendo no copo inclinado",
    "m\xE1quina batendo por 20 segundos",
    "close da caneca c\xF4nica",
    "funcion\xE1rio preparando no balc\xE3o",
    "compara\xE7\xE3o lado a lado: aguado x cremoso",
    "linha de produ\xE7\xE3o e teste de qualidade",
    "assist\xEAncia t\xE9cnica trabalhando"
  ],
  // claims with a number or a third-party name need proof before they go on video (briefing MMIX, item 2)
  differentiators: [
    "fabrica\xE7\xE3o pr\xF3pria em Londrina/PR",
    "assist\xEAncia t\xE9cnica pr\xF3pria"
  ],
  pendingClaims: [
    "mais de 20 anos de mercado",
    "mais de 4.000 m\xE1quinas em opera\xE7\xE3o",
    "caneca c\xF4nica exclusiva e o resultado dela na textura",
    "atende grandes redes e franquias"
  ],
  ctas: [
    "Fala com um especialista e v\xEA qual modelo combina com a sua opera\xE7\xE3o.",
    "Conhe\xE7a a linha completa e tira sua d\xFAvida com a nossa equipe.",
    "Me conta nos coment\xE1rios: como \xE9 o milk-shake a\xED na sua opera\xE7\xE3o?",
    "Solicita um or\xE7amento e compara na pr\xE1tica."
  ],
  noPrice: true
};
var CONTROLPOT_PROFILE = {
  displayName: "ControlPot",
  handle: "ControlPot",
  positioning: "Mixers profissionais para quem vive de milk-shake: resultado igual todo dia e opera\xE7\xE3o que n\xE3o para.",
  signature: "ControlPot",
  closingPhrase: "",
  voiceRules: [
    "fala de empres\xE1rio para empres\xE1rio, direto e pr\xE1tico",
    "uma obje\xE7\xE3o por v\xEDdeo, nunca v\xE1rias",
    "mostra prova, n\xE3o promete",
    "nunca fala pre\xE7o nem valor",
    "sem exagero e sem termos gen\xE9ricos de propaganda"
  ],
  kind: "empresa",
  business: CONTROLPOT_STRATEGY
};
var BUSINESS_WEEKDAY_BLOCKS = [
  { startTime: "11:00", title: "V\xEDdeo de venda (produto)", contentHint: "gancho, prova e chamada \u2014 30\u201360s", optional: false, format: "main_video" },
  { startTime: "14:30", title: "Prova visual / B-roll do produto", contentHint: "textura, m\xE1quina em uso, bastidor", optional: false, format: "broll" }
];
function businessRoutine(newId) {
  const blocks = [];
  for (let weekday = 1; weekday <= 5; weekday++) for (const b of BUSINESS_WEEKDAY_BLOCKS) blocks.push({ ...b, id: newId(), weekday });
  return blocks;
}
var PROFILE_TEMPLATES = [
  {
    id: "pessoal-rodrigo",
    label: "Pessoal \u2014 RodrigoSerra.me",
    description: 'Reflex\xE3o, vida real, academia e fam\xEDlia. Fecha com "E se der certo!".',
    name: "RodrigoSerra.me",
    profile: { ...RODRIGO_PROFILE, kind: "pessoal" },
    pillars: RODRIGO_PILLARS.map((p) => ({ ...p })),
    routine: rodrigoRoutine
  },
  {
    id: "empresa-controlpot",
    label: "Empresa \u2014 ControlPot",
    description: "V\xEDdeos que vendem mixer para empres\xE1rio: dor, obje\xE7\xE3o, prova e chamada. Nunca fala pre\xE7o.",
    name: "ControlPot",
    profile: CONTROLPOT_PROFILE,
    pillars: BUSINESS_PILLARS.map((p) => ({ ...p })),
    routine: businessRoutine
  },
  {
    id: "empresa-nova",
    label: "Outra empresa / produto",
    description: "Mesma estrat\xE9gia de venda; depois voc\xEA troca produto, dores e obje\xE7\xF5es.",
    name: "Minha empresa",
    profile: {
      ...CONTROLPOT_PROFILE,
      displayName: "Minha empresa",
      handle: "Minha empresa",
      signature: "Minha empresa",
      positioning: "Produto que resolve um problema real do meu cliente.",
      business: {
        brand: "Minha empresa",
        product: "meu produto",
        audience: "precisa resolver esse problema",
        pains: ["perde tempo com um processo que d\xE1 errado", "gasta duas vezes porque comprou o errado"],
        desires: ["resultado igual todo dia", "comprar uma vez e ficar tranquilo"],
        objections: [{ objection: "Est\xE1 caro", answer: "O barato que d\xE1 problema sai mais caro no fim do m\xEAs." }, { objection: "E se der problema?", answer: "A gente d\xE1 suporte e resolve r\xE1pido." }],
        proofs: ["produto em uso", "close no resultado", "cliente usando"],
        differentiators: ["atendimento de verdade"],
        ctas: ["Me chama e tira sua d\xFAvida.", "Conta nos coment\xE1rios como \xE9 a\xED com voc\xEA."],
        noPrice: true
      }
    },
    pillars: BUSINESS_PILLARS.map((p) => ({ ...p })),
    routine: businessRoutine
  }
];
var PRICE = /R\$\s*\d|\b\d+(?:[.,]\d+)?\s*reais\b|\bpre[çc]os?\b|\bparcela(?:s|do|mento)?\b|\bs[óo] \d|\b\d+\s*%\s*(?:off|de desconto)|\bdesconto de \d|\bcusta(?:m)? (?:s[óo] |apenas |a partir de )?\d/i;
function mentionsPrice(d) {
  const texts = [d.script, d.cta, d.screen_text, ...d.hook_options, ...Object.values(d.caption), ...d.versions.map((v) => v.script)];
  return texts.some((t) => PRICE.test(t));
}

// ../../packages/domain/src/ai/manual.ts
function buildManualPrompt(input) {
  const { system, user } = buildPrompt(input);
  const example = {
    title: "...",
    pillar: input.pillarName,
    format: input.format,
    duration_seconds: input.format === "thought" ? 12 : 60,
    structure: "confissao | pergunta | contraste | historia | conselho | observacao",
    topic: "...",
    key_phrase: "...",
    metaphor: "(pode ser vazio)",
    hook_options: ["gancho 1", "gancho 2", "gancho 3"],
    narrative: { e: "...", mas: "...", por_isso: "..." },
    script: "...",
    screen_text: "...",
    cta: "...",
    caption: { instagram: "...", tiktok: "...", facebook: "...", youtube_shorts: "..." },
    hashtags: ["#exemplo"],
    recording_suggestions: [{ scene: "...", duration_seconds: 3, location_hint: "..." }],
    versions: [{ duration_seconds: 30, script: "..." }]
  };
  return `${system}

${user}

Responda APENAS com um bloco JSON neste formato (sem coment\xE1rios):
${JSON.stringify(example, null, 2)}`;
}

// ../../packages/domain/src/ai/directorRules.ts
var MAX_HOOK_WORDS = 12;
var SCREEN_TEXT_WORDS = [2, 5];
var WORDS_PER_SECOND = 2.5;
var DURATION_SLACK = [0.6, 1.6];
var words = (s) => s.trim().split(/\s+/).filter(Boolean).length;
function directorIssues(draft) {
  const out = [];
  draft.hook_options.forEach((h, i) => {
    const n = words(h);
    if (n > MAX_HOOK_WORDS) out.push(`gancho ${i + 1} tem ${n} palavras (m\xE1ximo ${MAX_HOOK_WORDS})`);
  });
  const st = words(draft.screen_text);
  if (st < SCREEN_TEXT_WORDS[0] || st > SCREEN_TEXT_WORDS[1]) out.push(`screen_text tem ${st} palavra(s) (use ${SCREEN_TEXT_WORDS[0]} a ${SCREEN_TEXT_WORDS[1]})`);
  const spoken = words(draft.script);
  const estimated = Math.round(spoken / WORDS_PER_SECOND);
  const [lo, hi] = DURATION_SLACK;
  if (estimated < draft.duration_seconds * lo || estimated > draft.duration_seconds * hi) {
    out.push(`duration_seconds ${draft.duration_seconds}s n\xE3o bate com o texto (${spoken} palavras \u2248 ${estimated}s a ${WORDS_PER_SECOND} palavras/s)`);
  }
  return out;
}

// ../../packages/domain/src/studio.ts
var PRODUCTION_MODES = {
  demonstracao_mixer: {
    label: "A \xB7 Demonstra\xE7\xE3o de mixer",
    objetivo: "Mostrar o equipamento certo, instala\xE7\xE3o, preparo real, resultado e como escolher o modelo.",
    pillar: "demonstracao",
    needsSku: true,
    source: "expresso",
    shots: ["escolha_mixer", "ingredientes", "preparo", "textura", "copo", "cta"],
    guard: ["especifica\xE7\xE3o s\xF3 do cadastro atual do SKU", "sem pre\xE7o"],
    brief: "Demonstra\xE7\xE3o real na f\xE1brica: mostre o mixer filmado, o preparo sem cortes e o resultado. Explique para que opera\xE7\xE3o esse modelo serve. Especifica\xE7\xF5es s\xF3 do cadastro do SKU."
  },
  comece_balde: {
    label: "B \xB7 Comece com sorvete de balde",
    objetivo: "Opera\xE7\xE3o inicial simples: sorvete de massa de freezer + um mixer ControlPot, processo e evolu\xE7\xE3o.",
    pillar: "educacao",
    needsSku: true,
    source: "balde",
    shots: ["ingredientes", "medida", "preparo", "textura", "copo", "cta"],
    guard: ["n\xE3o prometer investimento, lucro ou retorno em n\xFAmero", "sem pre\xE7o"],
    brief: "Mostre como come\xE7ar com sorvete de balde e um mixer: equipamento e insumos necess\xE1rios, processo, padroniza\xE7\xE3o e como a opera\xE7\xE3o pode evoluir. N\xC3O cite valor de investimento, lucro nem retorno."
  },
  expresso_x_balde: {
    label: "C \xB7 Expresso \xD7 balde (did\xE1tico)",
    objetivo: "Comparar as duas formas de preparo com receita, quantidade, temperatura, modelo e tempo registrados.",
    pillar: "comparativo",
    needsSku: true,
    source: "ambos",
    shots: ["ingredientes", "medida", "preparo", "textura", "fala"],
    guard: ["n\xE3o dizer que uma \xE9 sempre melhor", "tempo e textura valem para esta demonstra\xE7\xE3o"],
    brief: "Compare expresso e balde lado a lado, como aula: custo, rotina e textura NO CONTEXTO demonstrado. N\xE3o diga que uma op\xE7\xE3o \xE9 sempre superior."
  },
  aula: {
    label: "D \xB7 Aula do curso",
    objetivo: "Roteiro de aula, materiais, plano de tomadas, cap\xEDtulos, revis\xE3o t\xE9cnica e vers\xE3o curta de divulga\xE7\xE3o.",
    pillar: "educacao",
    needsSku: true,
    source: "expresso",
    shots: ["fala", "ingredientes", "medida", "preparo", "textura", "limpeza"],
    guard: ["receita, medida e tempo s\xF3 os aprovados pelo Rodrigo", "o curso ensina de verdade; a venda nasce da demonstra\xE7\xE3o"],
    brief: "Aula pr\xE1tica do Curso de Milk Shake Profissional ControlPot. Ensine de verdade, passo a passo. Medidas, receita e tempo s\xF3 se estiverem na ficha aprovada; sen\xE3o diga 'ajuste pela textura'."
  },
  marketplace: {
    label: "E \xB7 Marketplace",
    objetivo: "V\xEDdeo do SKU e da variante exatos do an\xFAncio, com demonstra\xE7\xE3o real.",
    pillar: "demonstracao",
    needsSku: true,
    source: "expresso",
    shots: ["escolha_mixer", "preparo", "textura", "copo"],
    guard: ["SKU e variante do an\xFAncio", "conferir regras atuais do canal antes de exportar"],
    brief: "V\xEDdeo para an\xFAncio de marketplace do SKU exato: produto em uso, resultado, sem pre\xE7o, sem promessa. Curto e objetivo."
  },
  suporte: {
    label: "F \xB7 Suporte",
    objetivo: "Uso, limpeza, conserva\xE7\xE3o e d\xFAvidas recorrentes, com revis\xE3o t\xE9cnica.",
    pillar: "educacao",
    needsSku: true,
    source: "nenhum",
    shots: ["escolha_mixer", "limpeza", "fala"],
    guard: ["n\xE3o expor cliente, pedido ou OS", "caso individual s\xF3 com valida\xE7\xE3o t\xE9cnica"],
    brief: "V\xEDdeo de suporte geral: como usar, limpar e conservar o mixer. Nada de dados de cliente ou diagn\xF3stico individual."
  },
  autoridade: {
    label: "G \xB7 Autoridade",
    objetivo: "F\xE1brica, pessoas, fabrica\xE7\xE3o, testes, assist\xEAncia e demonstra\xE7\xF5es reais.",
    pillar: "autoridade",
    needsSku: false,
    source: "nenhum",
    shots: ["visao_fabrica", "fala", "preparo", "cta"],
    guard: ["n\xFAmero de m\xE1quinas, tempo de mercado, resultado t\xE9cnico ou franquia s\xF3 com prova"],
    brief: "Mostre a f\xE1brica real, as pessoas e os testes. Nenhum n\xFAmero (m\xE1quinas, anos, resultados) nem nome de franquia sem prova registrada."
  }
};
function pendingClaimsIn(text3, pendingClaims) {
  const t = norm(text3);
  const hits = pendingClaims.filter((c) => {
    const words2 = norm(c).split(" ").filter((w) => w.length > 3 || /\d/.test(w));
    const key = words2.filter((w) => /\d/.test(w));
    if (key.length) return key.some((k) => t.includes(k.replace(/\./g, "")) || t.includes(k));
    const found = words2.filter((w) => t.includes(w)).length;
    return found >= 2 && found / words2.length >= 0.5;
  });
  return hits;
}
var norm = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9. ]/g, " ").replace(/\s+/g, " ").trim();
var USE_TARGET_LABEL = {
  aula: "Aula completa",
  trecho_publico: "Trecho educativo p\xFAblico",
  curto_redes: "V\xEDdeo curto (redes)",
  pagina_produto: "P\xE1gina do produto",
  marketplace: "An\xFAncio de marketplace",
  suporte: "Resposta de suporte",
  campanha: "Campanha (CTA mixer ou curso)"
};
var FONTE_LABEL = { expresso: "sorvete expresso", balde: "sorvete de balde (massa de freezer)", ambos: "sorvete expresso e de balde", nenhum: "sem sorvete" };
function projectBrief(p) {
  const m = PRODUCTION_MODES[p.mode];
  return [
    `${m.label}. ${m.brief}`,
    p.skuNome || p.sku ? `Equipamento filmado: ${p.skuNome ?? ""}${p.sku ? ` (SKU ${p.sku})` : ""}.` : "",
    `Fonte de sorvete: ${FONTE_LABEL[p.fonteSorvete]}.`,
    p.aulaTitulo ? `Aula do curso: ${p.aulaTitulo}.` : "",
    p.receita ? `Receita/demonstra\xE7\xE3o (valores aprovados): ${p.receita}.` : "Sem receita aprovada: n\xE3o cite medidas nem tempo exatos, diga 'ajuste pela textura'.",
    p.derivedTarget ? `Formato de sa\xEDda: ${USE_TARGET_LABEL[p.derivedTarget]}.` : "",
    `Travas: ${m.guard.join("; ")}.`
  ].filter(Boolean).join(" ");
}

// ../../packages/domain/src/music.ts
var mk = (id, mood, title, artist, sha256, durationSec) => ({ id: `mixkit-${id}`, mood, title, artist, url: `https://assets.mixkit.co/music/${id}/${id}.mp3`, sha256, durationSec });
var MUSIC_LIBRARY = [
  mk(22, "reflexao", "Piano Reflections", "Ahjay Stelino", "7d58c4255d91f58e29e61520b6011cabd5a54b3e89b54646cebac9d37295bbec", 199),
  mk(601, "reflexao", "Skyline", "Eugenio Mininni", "2fcb36e7e58c4b6bc1505b7980237fdad86696589572a958bb6ee2084c592cc5", 206),
  mk(599, "reflexao", "Possible Dreams", "Eugenio Mininni", "ee6d055c20cccda716b6b63a154ef0dc825195b7061dc439abb8a623973f4798", 159),
  mk(32, "motivacional", "Driving Ambition", "Ahjay Stelino", "e3c88488e65b8c87a6f06120983ce2cb12ea3aeba99f8cadb7ee5d6d284ef2c6", 102),
  mk(31, "motivacional", "Dreaming Big", "Ahjay Stelino", "8c89819547b42a80750fb25f37a960a1f45f6fd66bc8d784ac817b98b002897c", 110),
  mk(34, "motivacional", "Raising Me Higher", "Ahjay Stelino", "619b82cea299230cca5beac36d049291a1cb2be8ce0afdafda3e06fb30d06525", 98),
  mk(1183, "treino", "Karma", "Michael Ramir C.", "56f331c37552486a1a31c65a443f1669ed37f7fb3bd99d9078d23ec55caa052f", 135),
  mk(470, "treino", "Golden Storm", "Diego Nava", "32e5a363ce84f0b633579d0b10cf3c758ae3c02f5121147a321e2483e3384e26", 95),
  mk(1e3, "treino", "I Can Hear Your Heartbeat", "Michael Ramir C.", "a23c959605dc4a53f7e3b8c8949fcc0d082c29989b944bb2a7f8d9601ddca0d1", 110),
  mk(839, "familia", "Tears of Joy", "Michael Ramir C.", "30717c4e8d2a954a6163477b831e5b8981b406d2c34d72820fce4d40a8686ddc", 140),
  mk(963, "familia", "Just Keep Walking", "Michael Ramir C.", "fa93f4808cecc643eee8d74647bd8b823991f2155672b7d37f3db79f9beb7e16", 125),
  mk(801, "familia", "Happy Home", "Michael Ramir C.", "76b82159ba1d6821a5ac9465e8ff19007446c1b657dfe53b5917fc8896b3bf21", 110),
  mk(2, "humor", "Comical", "Ahjay Stelino", "2f5ed23f2c51b5aa28b237563ee1249d12094fefce7afdaddee4f5a330e010cb", 114),
  mk(466, "humor", "Games Worldbeat", "Bernardo R.", "a1c70e5719bdfbe5dd8ec064939b27e3baed8c2b7f9375ae5b361e6ba71d4922", 107),
  mk(474, "empresa", "What About Action?", "Diego Nava", "4bcd99a13f3d71c6d356c2459f6f585f0d3f91ca8912aeef81ac626b8c8e3133", 117),
  mk(729, "empresa", "Pop Track 03", "Lily J", "0bb90793c71a07e6d698afdd434b32ffb4fe93dbbdb0577d3e71a4de80b0337b", 97),
  mk(1167, "empresa", "Close Up", "Michael Ramir C.", "a7f05a29d07a84d38072ccd2b35204bca812db86e75b2a837e71cc144d3e739b", 95),
  mk(441, "calmo", "Meditation", "Arulo", "6ffb81be8ab2447eb7b9357d6ae3d1b58eb8bc85376a724fafa5fe4d1acf562a", 118),
  mk(175, "calmo", "Digital Clouds", "Alejandro Maga\xF1a (A. M.)", "71cd4ea39edcc7532672bd97311abadfd318d00e7a828310a88b4f57fad9cd48", 101)
];

// ../../packages/domain/src/metrics.ts
function engagementRate(m) {
  return m.views > 0 ? (m.likes + m.comments + m.shares + m.saves) / m.views : 0;
}
function sharesPer1k(m) {
  return m.views > 0 ? m.shares / m.views * 1e3 : 0;
}

// src/mcp-tools.ts
var FORMAT_LABEL2 = { thought: "Pensamento do Dia", main_video: "V\xEDdeo principal", story: "Story", broll: "Cena de apoio" };
var DATE = /^\d{4}-\d{2}-\d{2}$/;
var MAX_PLAN_DAYS = 14;
var PILLAR_WINDOW_DAYS = 30;
var TOPIC_WINDOW_DAYS = 14;
var MIN_POSTS_FOR_CONCLUSIONS = 5;
var WEEKDAY = ["dom", "seg", "ter", "qua", "qui", "sex", "s\xE1b"];
var PROFILE_ARG = { profile_id: { type: "string", description: "id do perfil (listar_perfis). Sem ele: o perfil em que o link foi criado." } };
var obj = (properties, required = []) => ({ type: "object", properties: { ...PROFILE_ARG, ...properties }, required, additionalProperties: false });
var RO = { readOnlyHint: true };
var WRITE = { readOnlyHint: false, destructiveHint: false };
var MCP_TOOLS = [
  { name: "listar_perfis", title: "Perfis", description: "Lista os perfis do criador (pessoal, empresas\u2026) com id, nome, tipo e assinatura. Use o id em profile_id nas outras ferramentas.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: RO },
  { name: "perfil_e_estrategia", title: "Perfil e estrat\xE9gia", description: "Voz, posicionamento, fechamento, assinatura, temas com meta, rotina da semana e, se for empresa, produto, dores, obje\xE7\xF5es, provas e chamadas.", inputSchema: obj({}), annotations: RO },
  { name: "desempenho_dos_posts", title: "Desempenho dos posts", description: "Posts recentes: tema, formato, dia/hora e redes, visualiza\xE7\xF5es, curtidas, coment\xE1rios, compartilhamentos, salvamentos, engajamento e envios a cada mil.", inputSchema: obj({ limite: { type: "number", description: "quantos posts (padr\xE3o 30, m\xE1x. 100)" } }), annotations: RO },
  { name: "criar_plano", title: "Planejar dias", description: "Cria o plano (miss\xF5es e conte\xFAdos) a partir de uma data, para at\xE9 14 dias, seguindo a rotina e as metas dos temas. Dias j\xE1 planejados ficam como est\xE3o.", inputSchema: obj({ data_inicio: { type: "string", description: "AAAA-MM-DD (padr\xE3o: hoje)" }, dias: { type: "number", description: "1 a 14 (padr\xE3o 7)" } }), annotations: WRITE },
  { name: "conteudos_do_dia", title: "Conte\xFAdos do dia", description: "Conte\xFAdos de uma data (padr\xE3o: hoje, Bras\xEDlia) com id, formato, tema e se j\xE1 tem roteiro. Datas futuras sem plano: use criar_plano antes.", inputSchema: obj({ data: { type: "string", description: "AAAA-MM-DD (opcional)" } }), annotations: RO },
  { name: "ler_roteiro", title: "Ler roteiro salvo", description: "Devolve o roteiro j\xE1 salvo de um conte\xFAdo (JSON completo), as escolhas de edi\xE7\xE3o/m\xFAsica, os n\xFAmeros e se h\xE1 um roteiro do assistente esperando o app abrir.", inputSchema: obj({ content_id: { type: "string" } }, ["content_id"]), annotations: RO },
  { name: "instrucoes_do_roteiro", title: "Regras para o roteiro", description: "Regras do perfil (voz, formatos que viralizam, fechamento, o que n\xE3o repetir), temas abaixo da meta nos \xFAltimos 30 dias, assuntos bloqueados por 14 dias e o JSON exato.", inputSchema: obj({ content_id: { type: "string", description: "id de conteudos_do_dia" }, acontecimento: { type: "string", description: "o que aconteceu hoje (opcional)" } }, ["content_id"]), annotations: RO },
  { name: "salvar_roteiro", title: "Salvar roteiro no app", description: "Valida (contrato, gancho \u2264 12 palavras, texto de tela 2\u20135 palavras, dura\xE7\xE3o coerente, sem repetir, sem pre\xE7o/alega\xE7\xE3o sem prova no comercial) e envia ao app. Se falhar, devolve o que corrigir.", inputSchema: obj({ content_id: { type: "string" }, roteiro: { type: "object", description: "o JSON completo do roteiro" } }, ["content_id", "roteiro"]), annotations: WRITE },
  { name: "registrar_melhoria", title: "Registrar melhoria", description: "Manda uma sugest\xE3o de melhoria do app/conector para o backlog do desenvolvedor, com contexto e crit\xE9rio de aceite. Use para toda recomenda\xE7\xE3o de mudan\xE7a no sistema.", inputSchema: obj({ titulo: { type: "string" }, descricao: { type: "string", description: "o problema, a proposta e o crit\xE9rio de aceite" }, prioridade: { type: "string", enum: ["baixa", "media", "alta"] } }, ["titulo", "descricao"]), annotations: WRITE },
  { name: "listar_melhorias", title: "Melhorias pedidas", description: "Melhorias j\xE1 registradas e o andamento (nova, no backlog, feita, recusada).", inputSchema: obj({}), annotations: RO }
];
var text2 = (t, isError = false) => ({ content: [{ type: "text", text: t }], ...isError ? { isError: true } : {} });
function todayBrasilia(now = /* @__PURE__ */ new Date()) {
  return new Date(now.getTime() - 3 * 60 * 60 * 1e3).toISOString().slice(0, 10);
}
var brt = (iso) => {
  const d = new Date(new Date(iso).getTime() - 3 * 60 * 60 * 1e3).toISOString();
  return `${WEEKDAY[new Date(d.slice(0, 10)).getUTCDay()]} ${d.slice(0, 10)} ${d.slice(11, 16)}`;
};
async function describeStrategy(store) {
  const [p, s] = await Promise.all([store.profile(), store.strategy()]);
  const lines = [
    `Perfil: ${p.displayName} (${p.kind === "empresa" ? "empresa" : "pessoal"}) \xB7 assinatura ${p.signature}`,
    `Posicionamento: ${p.positioning}`,
    `Voz: ${p.voiceRules.join("; ")}`,
    p.closingPhrase ? `Fechamento obrigat\xF3rio: "${p.closingPhrase}"` : "",
    `Temas e meta: ${s.pillars.map((x) => `${x.name} ${x.targetPercent}%`).join(" \xB7 ")}`,
    `Rotina (hor\xE1rio de Bras\xEDlia): ${s.routine.map((r) => `${WEEKDAY[r.weekday]} ${r.startTime} ${r.title} (${FORMAT_LABEL2[r.format] ?? r.format})`).join(" \xB7 ") || "sem rotina"}`
  ];
  const b = p.kind === "empresa" ? p.business : void 0;
  if (b) {
    lines.push(
      `Produto: ${b.product} \xB7 cliente: ${b.audience}`,
      `Dores: ${b.pains.join("; ")}`,
      `Obje\xE7\xF5es: ${b.objections.map((o) => `${o.objection} \u2192 ${o.answer}`).join("; ")}`,
      `Provas para filmar: ${b.proofs.join("; ")}`,
      `Diferenciais comprovados: ${b.differentiators.join("; ")}`,
      b.pendingClaims?.length ? `N\xC3O afirmar (sem prova): ${b.pendingClaims.join("; ")}` : "",
      `Chamadas: ${b.ctas.join("; ")}`,
      b.noPrice ? "Nunca falar pre\xE7o." : ""
    );
  }
  return lines.filter(Boolean).join("\n");
}
async function describePosts(store, limit) {
  const posts = await store.posts(limit);
  if (!posts.length) return "Ainda n\xE3o h\xE1 posts registrados. O app anota a hora ao tocar em POSTAR e os n\xFAmeros em \u201CComo foi este post?\u201D.";
  const rows = await Promise.all(posts.map(async (x) => {
    const m = x.metrics;
    const nums = m ? `${m.views} visualiza\xE7\xF5es \xB7 ${m.likes} curtidas \xB7 ${m.comments} coment\xE1rios \xB7 ${m.shares} compartilhamentos \xB7 ${m.saves} salvamentos \xB7 engajamento ${(engagementRate(m) * 100).toFixed(1)}% \xB7 ${sharesPer1k(m).toFixed(1)} envios/mil` : "sem n\xFAmeros anotados";
    const when = x.postedAt ? `postado ${brt(x.postedAt)}${x.postedTo.length ? ` em ${x.postedTo.join(", ")}` : ""}` : `planejado para ${x.date} (hora de postagem n\xE3o registrada)`;
    return `- "${x.title}" \xB7 ${await store.pillarName(x.pillarSlug)} \xB7 ${FORMAT_LABEL2[x.format] ?? x.format} \xB7 ${when} \xB7 ${nums}`;
  }));
  const withNumbers = posts.filter((x) => x.metrics).length;
  const warn = withNumbers < MIN_POSTS_FOR_CONCLUSIONS ? "\nAten\xE7\xE3o: poucos posts com n\xFAmeros \u2014 conclus\xF5es sobre hor\xE1rio e tema ainda s\xE3o fracas." : "";
  return `${posts.length} posts (${withNumbers} com n\xFAmeros):
${rows.join("\n")}${warn}`;
}
async function pillarDeficit(store) {
  const [{ pillars }, counts] = await Promise.all([store.strategy(), store.pillarCounts(PILLAR_WINDOW_DAYS)]);
  const total = Object.values(counts).reduce((a, n) => a + n, 0);
  if (!pillars.length) return "";
  const rows = pillars.map((p) => {
    const done = total ? Math.round((counts[p.slug] ?? 0) / total * 100) : 0;
    return { name: p.name, target: p.targetPercent, done, gap: p.targetPercent - done };
  }).sort((a, b) => b.gap - a.gap);
  return `Temas nos \xFAltimos ${PILLAR_WINDOW_DAYS} dias (meta \xD7 feito, ${total} roteiro(s)) \u2014 priorize os primeiros:
${rows.map((r) => `- ${r.name}: meta ${r.target}% \xB7 feito ${r.done}%${r.gap > 0 ? ` (faltam ${r.gap} pontos)` : ""}`).join("\n")}`;
}
async function blockedTopics(store) {
  const topics = await store.recentTopics(TOPIC_WINDOW_DAYS);
  if (!topics.length) return "";
  const counts = /* @__PURE__ */ new Map();
  for (const t of topics) {
    const k = t.trim().toLowerCase();
    if (k) counts.set(k, (counts.get(k) ?? 0) + 1);
  }
  const list = [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([t, n]) => `- ${t}${n > 1 ? ` (${n}x)` : ""}`);
  return `Assuntos BLOQUEADOS (usados nos \xFAltimos ${TOPIC_WINDOW_DAYS} dias \u2014 escolha outro):
${list.join("\n")}`;
}
function clampDays(v) {
  return typeof v === "number" && v >= 1 ? Math.min(MAX_PLAN_DAYS, Math.floor(v)) : 7;
}
async function callProfileTool(store, name, args, now) {
  if (name === "perfil_e_estrategia") return text2(await describeStrategy(store));
  if (name === "desempenho_dos_posts") {
    const n = typeof args.limite === "number" && args.limite > 0 ? Math.min(100, Math.floor(args.limite)) : 30;
    return text2(await describePosts(store, n));
  }
  if (name === "criar_plano") {
    const start = typeof args.data_inicio === "string" && DATE.test(args.data_inicio) ? args.data_inicio : todayBrasilia(now);
    const days = await store.planDays(start, clampDays(args.dias));
    const lines = await Promise.all(days.map(async (d) => {
      const items = await Promise.all(d.items.map(async (c) => `  \xB7 id ${c.id} \xB7 ${FORMAT_LABEL2[c.format] ?? c.format} \xB7 ${await store.pillarName(c.pillarSlug)}${c.hasScript ? " \xB7 j\xE1 tem roteiro" : ""}`));
      return `${d.date}${d.created ? " (plano criado agora)" : ""}:
${items.join("\n") || "  \xB7 sem grava\xE7\xE3o de roteiro neste dia"}`;
    }));
    return text2(`Plano:
${lines.join("\n")}
Use instrucoes_do_roteiro e salvar_roteiro em cada id. O app mostra estes mesmos conte\xFAdos no dia.`);
  }
  if (name === "conteudos_do_dia") {
    const date = typeof args.data === "string" && DATE.test(args.data) ? args.data : todayBrasilia(now);
    const items = await store.contentsOn(date);
    if (!items.length) return text2(`Nada planejado para ${date}. Use criar_plano com data_inicio ${date} (ou o criador abre o Post.ai no dia).`);
    const lines = await Promise.all(items.map(async (c) => `- id ${c.id} \xB7 ${FORMAT_LABEL2[c.format] ?? c.format} \xB7 tema: ${await store.pillarName(c.pillarSlug)} \xB7 ${c.hasScript ? "j\xE1 tem roteiro (use ler_roteiro; salvar substitui)" : "sem roteiro"}`));
    return text2(`Conte\xFAdos de ${date}:
${lines.join("\n")}`);
  }
  if (name === "registrar_melhoria") {
    const titulo = String(args.titulo ?? "").trim().slice(0, 140);
    const descricao = String(args.descricao ?? "").trim().slice(0, 4e3);
    const prioridade = ["baixa", "media", "alta"].includes(String(args.prioridade)) ? String(args.prioridade) : "media";
    if (titulo.length < 3 || descricao.length < 3) return text2("D\xEA um t\xEDtulo e uma descri\xE7\xE3o (problema, proposta e crit\xE9rio de aceite).", true);
    const id2 = await store.saveImprovement({ titulo, descricao, prioridade });
    return text2(`Melhoria registrada (id ${id2}). Ela entra no backlog do desenvolvedor; acompanhe com listar_melhorias.`);
  }
  if (name === "listar_melhorias") {
    const list = await store.improvements();
    if (!list.length) return text2("Nenhuma melhoria registrada ainda.");
    return text2(list.map((m) => `- [${m.status}] ${m.titulo} (prioridade ${m.prioridade}${m.issueNumber ? ` \xB7 item #${m.issueNumber}` : ""})`).join("\n"));
  }
  const id = typeof args.content_id === "string" ? args.content_id : "";
  const content = id ? await store.content(id) : null;
  if (!content) return text2("Conte\xFAdo n\xE3o encontrado neste perfil. Use um id de conteudos_do_dia ou criar_plano.", true);
  if (name === "ler_roteiro") {
    const s = await store.readScript(content.id);
    return text2(JSON.stringify({ content_id: content.id, data: content.date, formato: content.format, tema: await store.pillarName(content.pillarSlug), ...s }, null, 2));
  }
  if (content.format !== "thought" && content.format !== "main_video") return text2("Este conte\xFAdo n\xE3o usa roteiro falado (\xE9 cena de apoio/story).", true);
  if (name === "instrucoes_do_roteiro") {
    const [profile, pillarName, recentSummaries, deficit, blocked] = await Promise.all([
      store.profile(),
      store.pillarName(content.pillarSlug),
      store.recentSummaries(),
      pillarDeficit(store),
      blockedTopics(store)
    ]);
    const eventText = typeof args.acontecimento === "string" && args.acontecimento.trim() ? args.acontecimento.trim().slice(0, 1500) : null;
    const prompt = buildManualPrompt({ profile, pillarName, format: content.format, eventText, brief: content.project ? projectBrief(content.project) : null, recentSummaries, avoid: "" });
    return text2([prompt, deficit, blocked, "Regras do diretor: gancho \u2264 12 palavras; screen_text 2\u20135 palavras; duration_seconds \u2248 palavras do script \xF7 2,5."].filter(Boolean).join("\n\n"));
  }
  if (name === "salvar_roteiro") {
    const profile = await store.profile();
    const parsed = parseDraft({ ...args.roteiro, format: content.format });
    if (!parsed.ok) return text2(`O roteiro n\xE3o passou na valida\xE7\xE3o. Corrija e salve de novo:
- ${parsed.errors.join("\n- ")}`, true);
    const draft = finalizeDraft(parsed.draft, profile);
    const rules = directorIssues(draft);
    if (rules.length) return text2(`Ajuste e salve de novo:
- ${rules.join("\n- ")}`, true);
    const biz = profile.kind === "empresa" ? profile.business : void 0;
    if (biz?.noPrice && mentionsPrice(draft)) return text2("O roteiro fala pre\xE7o/valor. Neste perfil de empresa pre\xE7o n\xE3o aparece no v\xEDdeo: reescreva sem pre\xE7o.", true);
    const unproven = biz ? pendingClaimsIn(`${draft.script} ${draft.cta}`, biz.pendingClaims ?? []) : [];
    if (unproven.length) return text2(`O roteiro afirma algo ainda sem prova: ${unproven.join("; ")}. Reescreva sem isso.`, true);
    const report = checkRepetition(fingerprintsFor(draft), (await store.recentFingerprints()).filter((f) => f.contentItemId !== content.id));
    if (report.repeated) return text2(`Parece repetir conte\xFAdo recente. Mude isto e salve de novo:
- ${describeAvoidance(report).join("\n- ")}`, true);
    await store.saveDraft(content.id, draft);
    return text2(`Roteiro "${draft.title}" enviado para o Post.ai. Ele aparece no app ao abrir este conte\xFAdo.`);
  }
  return text2(`Ferramenta desconhecida: ${name}`, true);
}
async function callTool(ctx, name, args, now) {
  if (name === "listar_perfis") {
    const list = await ctx.profiles();
    return text2(list.map((p) => `- id ${p.id} \xB7 ${p.name} \xB7 ${p.kind}${p.id === ctx.defaultProfileId ? " (padr\xE3o deste link)" : ""} \xB7 assinatura ${p.signature}`).join("\n") || "Nenhum perfil.");
  }
  const profileId = typeof args.profile_id === "string" && args.profile_id ? args.profile_id : ctx.defaultProfileId;
  const store = await ctx.store(profileId);
  if (!store) return text2("Perfil n\xE3o encontrado para este link. Use um id de listar_perfis.", true);
  return callProfileTool(store, name, args, now);
}

// src/mcp.ts
var MCP_PROTOCOL_VERSIONS = ["2025-06-18", "2025-03-26", "2024-11-05"];
var SERVER_INFO = { name: "postai", title: "Post.ai", version: "2.0.0" };
var INSTRUCTIONS = [
  "Voc\xEA \xE9 o DIRETOR DE GRAVA\xC7\xD5ES do criador no Post.ai (v\xEDdeos curtos; v\xE1rios perfis \u2014 pessoal e empresas).",
  "Crit\xE9rio de sucesso: resultado medido (reten\xE7\xE3o, envios, salvamentos, seguidores; nos comerciais, leads e vendas). Nunca prometa viraliza\xE7\xE3o.",
  "Sempre comece por listar_perfis e use profile_id do perfil certo; nunca misture dados entre perfis.",
  "Antes de decidir: perfil_e_estrategia e desempenho_dos_posts; se tiver busca na web, pesquise o que est\xE1 em alta no nicho agora.",
  "Planejar: criar_plano (at\xE9 14 dias) \u2192 para cada conte\xFAdo, ler_roteiro (se j\xE1 tiver) \u2192 instrucoes_do_roteiro (siga \xC0 RISCA voz, temas abaixo da meta, assuntos bloqueados e o JSON) \u2192 salvar_roteiro. Se voltar erro, corrija o apontado e salve de novo.",
  "Hor\xE1rio e sequ\xEAncia: baseie-se nos hor\xE1rios dos posts com mais visualiza\xE7\xF5es e envios; diga quando h\xE1 poucos dados.",
  "Toda recomenda\xE7\xE3o de mudan\xE7a no app ou no conector vai por registrar_melhoria (com crit\xE9rio de aceite).",
  "Nunca invente n\xFAmeros, pre\xE7o, prazo ou prova; n\xE3o exponha dados de crian\xE7as; fechamento do perfil pessoal \xE9 exatamente o configurado. Responda em portugu\xEAs do Brasil, simples."
].join("\n");
async function handleMcp(msg, ctx, now = /* @__PURE__ */ new Date()) {
  const req = msg;
  if (!req || req.jsonrpc !== "2.0" || typeof req.method !== "string") return { jsonrpc: "2.0", id: null, error: { code: -32600, message: "Invalid Request" } };
  if (req.id === void 0) return null;
  const ok = (result) => ({ jsonrpc: "2.0", id: req.id, result });
  switch (req.method) {
    case "initialize": {
      const asked = String(req.params?.protocolVersion ?? "");
      const protocolVersion = MCP_PROTOCOL_VERSIONS.includes(asked) ? asked : MCP_PROTOCOL_VERSIONS[0];
      return ok({ protocolVersion, capabilities: { tools: { listChanged: false } }, serverInfo: SERVER_INFO, instructions: INSTRUCTIONS });
    }
    case "ping":
      return ok({});
    case "tools/list":
      return ok({ tools: MCP_TOOLS });
    case "tools/call": {
      const name = String(req.params?.name ?? "");
      const args = req.params?.arguments ?? {};
      try {
        return ok(await callTool(ctx, name, args, now));
      } catch (e) {
        return ok(text2(`N\xE3o consegui falar com o Post.ai agora (${e instanceof Error ? e.message : "erro"}). Tente de novo em instantes.`, true));
      }
    }
    default:
      return { jsonrpc: "2.0", id: req.id, error: { code: -32601, message: `Method not found: ${req.method}` } };
  }
}

// src/adapters.ts
import { createClient } from "npm:@supabase/supabase-js@2";
var MEMORY_WINDOW = 120;
function supabaseMemory(db, userId) {
  return {
    async canWrite(ws) {
      const { data, error } = await db.rpc("can_write_workspace", { ws });
      if (error) throw error;
      return data === true;
    },
    async profile(ws) {
      const { data, error } = await db.from("creator_profiles").select("*").eq("workspace_id", ws).maybeSingle();
      if (error) throw error;
      if (!data) throw Object.assign(new Error("workspace not found"), { status: 404 });
      return {
        displayName: data.display_name,
        handle: data.handle ?? data.display_name,
        positioning: data.positioning ?? "",
        signature: data.signature ?? data.handle ?? "",
        closingPhrase: data.closing_phrase ?? "",
        voiceRules: data.voice_rules?.length ? data.voice_rules : RODRIGO_PROFILE.voiceRules,
        // kind + sales strategy of a business profile live in creator_profiles.tone
        kind: data.tone?.kind === "empresa" ? "empresa" : "pessoal",
        business: data.tone?.kind === "empresa" ? data.tone.business : void 0
      };
    },
    async pillarName(ws, slug) {
      const { data } = await db.from("content_pillars").select("name").eq("workspace_id", ws).eq("slug", slug).maybeSingle();
      return data?.name ?? slug;
    },
    async recentFingerprints(ws) {
      const { data, error } = await db.from("content_fingerprints").select("fingerprint_type, fingerprint, content_item_id, created_at").eq("workspace_id", ws).order("created_at", { ascending: false }).limit(MEMORY_WINDOW);
      if (error) throw error;
      return (data ?? []).map((r) => ({ type: r.fingerprint_type, value: r.fingerprint, contentItemId: r.content_item_id, createdAt: r.created_at }));
    },
    async recentSummaries(ws) {
      const { data } = await db.from("scripts").select("draft").eq("workspace_id", ws).order("created_at", { ascending: false }).limit(10);
      return (data ?? []).filter((r) => r.draft?.topic).map((r) => summarizeForMemory(r.draft));
    },
    async saveRun(run) {
      const { error } = await db.from("generation_runs").insert({
        workspace_id: run.workspaceId,
        content_item_id: null,
        source: run.model.startsWith("gemini") ? "gemini" : "openai",
        model: run.model,
        prompt_version: run.promptVersion,
        request: run.request,
        response: run.response,
        accepted: run.accepted,
        rejection_reason: run.rejectionReason,
        repetition: run.repetition ?? {},
        latency_ms: run.latencyMs,
        created_by: userId
      });
      if (error) console.warn(JSON.stringify({ level: "warn", msg: "generation_run not saved", code: error.code }));
    }
  };
}

// src/mcp-store.ts
var COLS = "id, format, pillar_slug, title, plan_date, structured_payload";
var asProject = (p) => p?.project ?? null;
var daysAgo = (n) => new Date(Date.now() - n * 24 * 60 * 60 * 1e3).toISOString();
var addDays = (dateKey, n) => new Date(Date.parse(`${dateKey}T12:00:00Z`) + n * 864e5).toISOString().slice(0, 10);
var brtDayRange = (dateKey) => {
  const start = new Date(Date.parse(`${dateKey}T00:00:00Z`) - BRASILIA_OFFSET_MIN * 6e4);
  return [start.toISOString(), new Date(start.getTime() + 864e5).toISOString()];
};
var WRITE_ROLES = ["owner", "editor"];
function supabaseMcpStore(db, workspaceId, userId) {
  const memory = supabaseMemory(db, userId);
  const withScript = async (rows) => {
    const ids = rows.map((r) => r.id);
    const { data } = ids.length ? await db.from("scripts").select("content_item_id").in("content_item_id", ids) : { data: [] };
    const scripted = new Set((data ?? []).map((s) => s.content_item_id));
    return rows.map((r) => ({
      id: r.id,
      format: r.format,
      pillarSlug: r.pillar_slug ?? "",
      title: r.title,
      date: r.plan_date ?? "",
      hasScript: scripted.has(r.id),
      project: asProject(r.structured_payload)
    }));
  };
  const store = {
    async contentsOn(date) {
      const { data, error } = await db.from("content_items").select(COLS).eq("workspace_id", workspaceId).eq("plan_date", date).order("scheduled_for");
      if (error) throw new Error(error.message);
      return withScript(data ?? []);
    },
    async readScript(contentId) {
      const [script, content, pending] = await Promise.all([
        db.from("scripts").select("draft").eq("workspace_id", workspaceId).eq("content_item_id", contentId).order("updated_at", { ascending: false }).limit(1).maybeSingle(),
        db.from("content_items").select("structured_payload").eq("workspace_id", workspaceId).eq("id", contentId).maybeSingle(),
        db.from("assistant_drafts").select("id", { count: "exact", head: true }).eq("workspace_id", workspaceId).eq("content_item_id", contentId).is("consumed_at", null)
      ]);
      const sp = content.data?.structured_payload ?? {};
      return {
        draft: script.data?.draft ?? null,
        edit: sp.edit ?? null,
        metrics: sp.metrics ?? null,
        postedAt: typeof sp.posted_at === "string" ? sp.posted_at : null,
        pendingFromAssistant: (pending.count ?? 0) > 0
      };
    },
    async planDays(startDate, days) {
      const out = [];
      const [pillarRows, blockRows, recentRows] = await Promise.all([
        db.from("content_pillars").select("slug, name, target_percent, active").eq("workspace_id", workspaceId),
        db.from("routine_blocks").select("id, weekday, start_time, title, content_hint, optional, default_format").eq("workspace_id", workspaceId),
        db.from("content_items").select("pillar_slug").eq("workspace_id", workspaceId).order("plan_date", { ascending: false }).limit(30)
      ]);
      const err = pillarRows.error ?? blockRows.error ?? recentRows.error;
      if (err) throw new Error(err.message);
      const pillars = (pillarRows.data ?? []).map((p) => ({ slug: p.slug, name: p.name, targetPercent: Number(p.target_percent), active: p.active }));
      const routine = (blockRows.data ?? []).map((b) => ({
        id: b.id,
        weekday: b.weekday,
        startTime: String(b.start_time).slice(0, 5),
        title: b.title,
        contentHint: b.content_hint,
        optional: b.optional,
        format: b.default_format
      }));
      const history = (recentRows.data ?? []).map((r) => r.pillar_slug).filter(Boolean).reverse();
      for (let i = 0; i < days; i++) {
        const date = addDays(startDate, i);
        const [from, to] = brtDayRange(date);
        const tasks = await db.from("recording_tasks").select("id").eq("workspace_id", workspaceId).gte("scheduled_for", from).lt("scheduled_for", to).limit(1);
        if (tasks.error) throw new Error(tasks.error.message);
        const existing = await store.contentsOn(date);
        if (existing.length || tasks.data?.length) {
          out.push({ date, created: false, items: existing });
          continue;
        }
        const plan = buildDayPlan({ date: /* @__PURE__ */ new Date(0), dateKey: date, utcOffsetMinutes: BRASILIA_OFFSET_MIN, workspaceId, routine, pillars, recentPillarSlugs: history, newId: () => crypto.randomUUID(), now: (/* @__PURE__ */ new Date()).toISOString() });
        history.push(...plan.contentItems.map((c) => c.pillarSlug));
        if (plan.contentItems.length) {
          const ci = await db.from("content_items").insert(plan.contentItems.map((c) => ({
            id: c.id,
            workspace_id: workspaceId,
            pillar_slug: c.pillarSlug,
            plan_date: c.date,
            scheduled_for: c.scheduledFor,
            format: c.format,
            title: c.title,
            status: c.status,
            structured_payload: {}
          })));
          if (ci.error) throw new Error(ci.error.message);
        }
        if (plan.tasks.length) {
          const rt = await db.from("recording_tasks").insert(plan.tasks.map((t) => ({
            id: t.id,
            workspace_id: workspaceId,
            content_item_id: t.contentItemId,
            scheduled_for: t.scheduledFor,
            title: t.title,
            kind: t.kind,
            hint: t.hint,
            suggested_duration_seconds: t.suggestedDurationSeconds,
            optional: t.optional,
            status: t.status,
            updated_at: t.updatedAt
          })));
          if (rt.error) throw new Error(rt.error.message);
        }
        out.push({ date, created: true, items: await store.contentsOn(date) });
      }
      return out;
    },
    async pillarCounts(days) {
      const scripts = await db.from("scripts").select("content_item_id").eq("workspace_id", workspaceId).gte("created_at", daysAgo(days));
      if (scripts.error) throw new Error(scripts.error.message);
      const ids = [...new Set((scripts.data ?? []).map((r) => r.content_item_id).filter(Boolean))];
      if (!ids.length) return {};
      const items = await db.from("content_items").select("pillar_slug").eq("workspace_id", workspaceId).in("id", ids);
      if (items.error) throw new Error(items.error.message);
      const counts = {};
      for (const r of items.data ?? []) if (r.pillar_slug) counts[r.pillar_slug] = (counts[r.pillar_slug] ?? 0) + 1;
      return counts;
    },
    async recentTopics(days) {
      const { data, error } = await db.from("scripts").select("draft").eq("workspace_id", workspaceId).gte("created_at", daysAgo(days)).order("created_at", { ascending: false }).limit(60);
      if (error) throw new Error(error.message);
      return (data ?? []).map((r) => String(r.draft?.topic ?? "")).filter(Boolean);
    },
    async saveImprovement(i) {
      const { data, error } = await db.from("melhorias").insert({ workspace_id: workspaceId, user_id: userId, ...i }).select("id").single();
      if (error) throw new Error(error.message);
      return data.id;
    },
    async improvements() {
      const { data, error } = await db.from("melhorias").select("id, titulo, prioridade, status, issue_number, created_at").eq("workspace_id", workspaceId).order("created_at", { ascending: false }).limit(30);
      if (error) throw new Error(error.message);
      return (data ?? []).map((m) => ({ id: m.id, titulo: m.titulo, prioridade: m.prioridade, status: m.status, issueNumber: m.issue_number, createdAt: m.created_at }));
    },
    async content(id) {
      const { data, error } = await db.from("content_items").select(COLS).eq("workspace_id", workspaceId).eq("id", id).maybeSingle();
      if (error) throw new Error(error.message);
      return data ? (await withScript([data]))[0] : null;
    },
    profile: () => memory.profile(workspaceId),
    pillarName: (slug) => memory.pillarName(workspaceId, slug),
    recentFingerprints: () => memory.recentFingerprints(workspaceId),
    recentSummaries: () => memory.recentSummaries(workspaceId),
    async saveDraft(contentId, draft) {
      const { error } = await db.from("assistant_drafts").insert({ workspace_id: workspaceId, content_item_id: contentId, draft, source: "mcp" });
      if (error) throw new Error(error.message);
    },
    async strategy() {
      const [pillars, blocks] = await Promise.all([
        db.from("content_pillars").select("slug, name, target_percent, active").eq("workspace_id", workspaceId),
        db.from("routine_blocks").select("weekday, start_time, title, default_format").eq("workspace_id", workspaceId).order("weekday").order("start_time")
      ]);
      if (pillars.error ?? blocks.error) throw new Error((pillars.error ?? blocks.error).message);
      return {
        pillars: (pillars.data ?? []).filter((p) => p.active).map((p) => ({ slug: p.slug, name: p.name, targetPercent: Number(p.target_percent) })),
        routine: (blocks.data ?? []).map((b) => ({ weekday: b.weekday, startTime: String(b.start_time).slice(0, 5), title: b.title, format: b.default_format }))
      };
    },
    async posts(limit) {
      const { data, error } = await db.from("content_items").select(COLS).eq("workspace_id", workspaceId).or("structured_payload->>posted_at.not.is.null,structured_payload->>metrics.not.is.null").order("plan_date", { ascending: false }).limit(limit);
      if (error) throw new Error(error.message);
      return (data ?? []).map((r) => {
        const p = r.structured_payload ?? {};
        return {
          id: r.id,
          title: r.title,
          pillarSlug: r.pillar_slug ?? "",
          format: r.format,
          date: r.plan_date ?? "",
          postedAt: typeof p.posted_at === "string" ? p.posted_at : null,
          postedTo: Array.isArray(p.posted_to) ? p.posted_to : [],
          metrics: p.metrics ?? null
        };
      });
    }
  };
  return store;
}
function supabaseMcpContext(db, userId, defaultProfileId) {
  const canWrite = async (workspaceId) => {
    const { data } = await db.from("workspace_members").select("role").eq("workspace_id", workspaceId).eq("user_id", userId).maybeSingle();
    return Boolean(data && WRITE_ROLES.includes(data.role));
  };
  return {
    defaultProfileId,
    async profiles() {
      const { data, error } = await db.from("workspace_members").select("workspace_id, role, workspaces(name, deleted_at)").eq("user_id", userId);
      if (error) throw new Error(error.message);
      const rows = data ?? [];
      const mine = rows.filter((r) => WRITE_ROLES.includes(r.role) && r.workspaces && !r.workspaces.deleted_at);
      const ids = mine.map((r) => r.workspace_id);
      const prof = ids.length ? await db.from("creator_profiles").select("workspace_id, signature, tone").in("workspace_id", ids) : { data: [] };
      const byWs = new Map((prof.data ?? []).map((p) => [p.workspace_id, p]));
      return mine.map((r) => ({
        id: r.workspace_id,
        name: r.workspaces.name,
        kind: byWs.get(r.workspace_id)?.tone?.kind === "empresa" ? "empresa" : "pessoal",
        signature: byWs.get(r.workspace_id)?.signature ?? ""
      }));
    },
    async store(profileId) {
      return /^[0-9a-f-]{36}$/i.test(profileId) && await canWrite(profileId) ? supabaseMcpStore(db, profileId, userId) : null;
    }
  };
}
async function sha256Hex(s) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function resolveMcpToken(db, token) {
  if (!/^[0-9a-f]{64}$/.test(token)) return null;
  const { data } = await db.from("mcp_tokens").select("id, workspace_id, user_id").eq("token_hash", await sha256Hex(token)).is("revoked_at", null).maybeSingle();
  if (!data) return null;
  const member = await db.from("workspace_members").select("role").eq("workspace_id", data.workspace_id).eq("user_id", data.user_id).maybeSingle();
  if (!member.data || member.data.role === "viewer") return null;
  await db.from("mcp_tokens").update({ last_used_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", data.id);
  return { workspaceId: data.workspace_id, userId: data.user_id };
}

// src/mcp-edge.ts
var MAX_BODY = 256 * 1024;
var json = (status, body) => new Response(body === null ? null : JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
Deno.serve(async (req) => {
  if (req.method === "GET" || req.method === "DELETE") return new Response(null, { status: 405, headers: { Allow: "POST" } });
  if (req.method !== "POST") return json(405, { error: "method_not_allowed" });
  const token = new URL(req.url).pathname.split("/").filter(Boolean).pop() ?? "";
  const db = createClient2(Deno.env.get("SUPABASE_URL"), Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"), { auth: { persistSession: false } });
  const who = await resolveMcpToken(db, token).catch(() => null);
  if (!who) return json(404, { error: "link do conector inv\xE1lido ou desligado \u2014 crie outro no app (Configura\xE7\xF5es)" });
  const raw = await req.text();
  if (raw.length > MAX_BODY) return json(413, { error: "too_large" });
  let msg;
  try {
    msg = JSON.parse(raw);
  } catch {
    return json(400, { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } });
  }
  const ctx = supabaseMcpContext(db, who.userId, who.workspaceId);
  if (Array.isArray(msg)) {
    const out = (await Promise.all(msg.map((m) => handleMcp(m, ctx)))).filter(Boolean);
    return out.length ? json(200, out) : new Response(null, { status: 202 });
  }
  const res = await handleMcp(msg, ctx);
  return res ? json(200, res) : new Response(null, { status: 202 });
});
