-- Gemini (Google AI) as a script source, generated by the `generate` Edge Function.
alter table scripts drop constraint scripts_source_check;
alter table scripts add constraint scripts_source_check check (source in ('openai','gemini','local','manual'));
